version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: sunday
      timezone: "Asia/Shanghai"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      timezone: "Asia/Shanghai"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
      timezone: "Asia/Shanghai"

