/*
 * Lybic core API
 *
 * Lybic core API
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package lybic
// CreateProjectDto struct for CreateProjectDto
type CreateProjectDto struct {
	// Name of the project.
	Name string `json:"name"`
}
