// Code generated by OpenAPI Generator. DO NOT EDIT.
//
// lybic
//
// No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
//
// API version: 0.6.3
// Generated by: OpenAPI Generator (https://openapi-generator.tech)
//

package lybic

import (
	"encoding/json"
)

// GetSandboxResponseDtoConnectDetailsGatewayAddresses struct for GetSandboxResponseDtoConnectDetailsGatewayAddresses
type GetSandboxResponseDtoConnectDetailsGatewayAddresses struct {
	Address string `json:"address"`
	Port float32 `json:"port"`
	Name string `json:"name"`
	PreferredProviders []string `json:"preferredProviders"`
	GatewayType string `json:"gatewayType"`
}

// NewGetSandboxResponseDtoConnectDetailsGatewayAddresses instantiates a new GetSandboxResponseDtoConnectDetailsGatewayAddresses object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSandboxResponseDtoConnectDetailsGatewayAddresses(address string, port float32, name string, preferredProviders []string, gatewayType string, ) *GetSandboxResponseDtoConnectDetailsGatewayAddresses {
	this := GetSandboxResponseDtoConnectDetailsGatewayAddresses{}
	this.Address = address
	this.Port = port
	this.Name = name
	this.PreferredProviders = preferredProviders
	this.GatewayType = gatewayType
	return &this
}

// NewGetSandboxResponseDtoConnectDetailsGatewayAddressesWithDefaults instantiates a new GetSandboxResponseDtoConnectDetailsGatewayAddresses object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSandboxResponseDtoConnectDetailsGatewayAddressesWithDefaults() *GetSandboxResponseDtoConnectDetailsGatewayAddresses {
	this := GetSandboxResponseDtoConnectDetailsGatewayAddresses{}
	return &this
}

// GetAddress returns the Address field value
func (o *GetSandboxResponseDtoConnectDetailsGatewayAddresses) GetAddress() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *GetSandboxResponseDtoConnectDetailsGatewayAddresses) GetAddressOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *GetSandboxResponseDtoConnectDetailsGatewayAddresses) SetAddress(v string) {
	o.Address = v
}

// GetPort returns the Port field value
func (o *GetSandboxResponseDtoConnectDetailsGatewayAddresses) GetPort() float32 {
	if o == nil  {
		var ret float32
		return ret
	}

	return o.Port
}

// GetPortOk returns a tuple with the Port field value
// and a boolean to check if the value has been set.
func (o *GetSandboxResponseDtoConnectDetailsGatewayAddresses) GetPortOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Port, true
}

// SetPort sets field value
func (o *GetSandboxResponseDtoConnectDetailsGatewayAddresses) SetPort(v float32) {
	o.Port = v
}

// GetName returns the Name field value
func (o *GetSandboxResponseDtoConnectDetailsGatewayAddresses) GetName() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GetSandboxResponseDtoConnectDetailsGatewayAddresses) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *GetSandboxResponseDtoConnectDetailsGatewayAddresses) SetName(v string) {
	o.Name = v
}

// GetPreferredProviders returns the PreferredProviders field value
func (o *GetSandboxResponseDtoConnectDetailsGatewayAddresses) GetPreferredProviders() []string {
	if o == nil  {
		var ret []string
		return ret
	}

	return o.PreferredProviders
}

// GetPreferredProvidersOk returns a tuple with the PreferredProviders field value
// and a boolean to check if the value has been set.
func (o *GetSandboxResponseDtoConnectDetailsGatewayAddresses) GetPreferredProvidersOk() (*[]string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.PreferredProviders, true
}

// SetPreferredProviders sets field value
func (o *GetSandboxResponseDtoConnectDetailsGatewayAddresses) SetPreferredProviders(v []string) {
	o.PreferredProviders = v
}

// GetGatewayType returns the GatewayType field value
func (o *GetSandboxResponseDtoConnectDetailsGatewayAddresses) GetGatewayType() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.GatewayType
}

// GetGatewayTypeOk returns a tuple with the GatewayType field value
// and a boolean to check if the value has been set.
func (o *GetSandboxResponseDtoConnectDetailsGatewayAddresses) GetGatewayTypeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.GatewayType, true
}

// SetGatewayType sets field value
func (o *GetSandboxResponseDtoConnectDetailsGatewayAddresses) SetGatewayType(v string) {
	o.GatewayType = v
}

func (o GetSandboxResponseDtoConnectDetailsGatewayAddresses) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["address"] = o.Address
	}
	if true {
		toSerialize["port"] = o.Port
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["preferredProviders"] = o.PreferredProviders
	}
	if true {
		toSerialize["gatewayType"] = o.GatewayType
	}
	return json.Marshal(toSerialize)
}

type NullableGetSandboxResponseDtoConnectDetailsGatewayAddresses struct {
	value *GetSandboxResponseDtoConnectDetailsGatewayAddresses
	isSet bool
}

func (v NullableGetSandboxResponseDtoConnectDetailsGatewayAddresses) Get() *GetSandboxResponseDtoConnectDetailsGatewayAddresses {
	return v.value
}

func (v *NullableGetSandboxResponseDtoConnectDetailsGatewayAddresses) Set(val *GetSandboxResponseDtoConnectDetailsGatewayAddresses) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSandboxResponseDtoConnectDetailsGatewayAddresses) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSandboxResponseDtoConnectDetailsGatewayAddresses) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSandboxResponseDtoConnectDetailsGatewayAddresses(val *GetSandboxResponseDtoConnectDetailsGatewayAddresses) *NullableGetSandboxResponseDtoConnectDetailsGatewayAddresses {
	return &NullableGetSandboxResponseDtoConnectDetailsGatewayAddresses{value: val, isSet: true}
}

func (v NullableGetSandboxResponseDtoConnectDetailsGatewayAddresses) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSandboxResponseDtoConnectDetailsGatewayAddresses) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
