/*
 * Lybic core API
 *
 * Lybic core API
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package lybic

// CreateMachineImageDto struct for CreateMachineImageDto
type CreateMachineImageDto struct {
	// The sandbox ID to create image from.
	SandboxId string `json:"sandboxId"`
	// The name of the machine image.
	Name string `json:"name"`
	// Optional description of the machine image.
	Description *string `json:"description,omitempty"`
}
