// Code generated by OpenAPI Generator. DO NOT EDIT.
//
// lybic
//
// No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
//
// API version: 0.8
// Generated by: OpenAPI Generator (https://openapi-generator.tech)
//

package lybic

import (
	"github.com/lybic/lybic-sdk-go/pkg/json"
)

// ExtendSandboxDto struct for ExtendSandboxDto
type ExtendSandboxDto struct {
	// The new max life time of the sandbox (relative to the current time) in seconds. Should not less than 30 seconds or more than 24 hours. Note that the total maximum lifetime of a sandbox should not longer than 13 days.
	MaxLifeSeconds *float32 `json:"maxLifeSeconds,omitempty"`
}

// NewExtendSandboxDto instantiates a new ExtendSandboxDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExtendSandboxDto() *ExtendSandboxDto {
	this := ExtendSandboxDto{}
	var maxLifeSeconds float32 = 3600
	this.MaxLifeSeconds = &maxLifeSeconds
	return &this
}

// NewExtendSandboxDtoWithDefaults instantiates a new ExtendSandboxDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExtendSandboxDtoWithDefaults() *ExtendSandboxDto {
	this := ExtendSandboxDto{}
	var maxLifeSeconds float32 = 3600
	this.MaxLifeSeconds = &maxLifeSeconds
	return &this
}

// GetMaxLifeSeconds returns the MaxLifeSeconds field value if set, zero value otherwise.
func (o *ExtendSandboxDto) GetMaxLifeSeconds() float32 {
	if o == nil || o.MaxLifeSeconds == nil {
		var ret float32
		return ret
	}
	return *o.MaxLifeSeconds
}

// GetMaxLifeSecondsOk returns a tuple with the MaxLifeSeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExtendSandboxDto) GetMaxLifeSecondsOk() (*float32, bool) {
	if o == nil || o.MaxLifeSeconds == nil {
		return nil, false
	}
	return o.MaxLifeSeconds, true
}

// HasMaxLifeSeconds returns a boolean if a field has been set.
func (o *ExtendSandboxDto) HasMaxLifeSeconds() bool {
	if o != nil && o.MaxLifeSeconds != nil {
		return true
	}

	return false
}

// SetMaxLifeSeconds gets a reference to the given float32 and assigns it to the MaxLifeSeconds field.
func (o *ExtendSandboxDto) SetMaxLifeSeconds(v float32) {
	o.MaxLifeSeconds = &v
}

func (o ExtendSandboxDto) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.MaxLifeSeconds != nil {
		toSerialize["maxLifeSeconds"] = o.MaxLifeSeconds
	}
	return json.Marshal(toSerialize)
}

type NullableExtendSandboxDto struct {
	value *ExtendSandboxDto
	isSet bool
}

func (v NullableExtendSandboxDto) Get() *ExtendSandboxDto {
	return v.value
}

func (v *NullableExtendSandboxDto) Set(val *ExtendSandboxDto) {
	v.value = val
	v.isSet = true
}

func (v NullableExtendSandboxDto) IsSet() bool {
	return v.isSet
}

func (v *NullableExtendSandboxDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExtendSandboxDto(val *ExtendSandboxDto) *NullableExtendSandboxDto {
	return &NullableExtendSandboxDto{value: val, isSet: true}
}

func (v NullableExtendSandboxDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExtendSandboxDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
