/*
 * Lybic core API
 *
 * Lybic core API
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package lybic

// McpServerResponseDtoPolicy struct for McpServerResponseDtoPolicy
type McpServerResponseDtoPolicy struct {
	// The shape of the sandbox created by the MCP server.
	SandboxShape string `json:"sandboxShape"`
	// The maximum lifetime of a sandbox.
	SandboxMaxLifetimeSeconds float32 `json:"sandboxMaxLifetimeSeconds,omitempty"`
	// The maximum idle time of a sandbox.
	SandboxMaxIdleTimeSeconds float32 `json:"sandboxMaxIdleTimeSeconds,omitempty"`
	// Whether to create a new sandbox automatically when old sandbox is deleted. If not, new sandboxes will be created when calling computer use tools.
	SandboxAutoCreation bool `json:"sandboxAutoCreation,omitempty"`
	// Whether to expose recreate tool to LLMs.
	SandboxExposeRecreateTool bool `json:"sandboxExposeRecreateTool,omitempty"`
	// Whether to expose restart tool to LLMs.
	SandboxExposeRestartTool bool `json:"sandboxExposeRestartTool,omitempty"`
	// Whether to expose delete tool to LLMs.
	SandboxExposeDeleteTool bool `json:"sandboxExposeDeleteTool,omitempty"`
}
