/*
 * Lybic core API
 *
 * Lybic core API
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package lybic

// SandboxFileCopyResponseDto struct for SandboxFileCopyResponseDto
type SandboxFileCopyResponseDto struct {
	Results []SandboxFileCopyResponseDtoResults `json:"results"`
}
