/*
 * Lybic core API
 *
 * Lybic core API
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package lybic

// SandboxProcessResponseDto struct for SandboxProcessResponseDto
type SandboxProcessResponseDto struct {
	// stdout as base64-encoded bytes
	StdoutBase64 string `json:"stdoutBase64,omitempty"`
	// stderr as base64-encoded bytes
	StderrBase64 string `json:"stderrBase64,omitempty"`
	// Exit code
	ExitCode int `json:"exitCode"`
}
