/*
 * Lybic core API
 *
 * Lybic core API
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package lybic
// ParseRequestDto struct for ParseRequestDto
type ParseRequestDto struct {
	// The model to parse the input for
	Model string `json:"model"`
	// The text content to parse
	TextContent string `json:"textContent"`
}
