/*
 * Lybic core API
 *
 * Lybic core API
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package lybic

// ParseTextRequestDto struct for ParseTextRequestDto
type ParseTextRequestDto struct {
	// The text content to parse
	TextContent string `json:"textContent"`
}
