/*
 * Lybic core API
 *
 * Lybic core API
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package lybic

// CreateSandboxFromImageDto struct for CreateSandboxFromImageDto
type CreateSandboxFromImageDto struct {
	// The machine image ID to create sandbox from.
	ImageId string `json:"imageId"`
	// The name of the sandbox.
	Name string `json:"name"`
	// The maximum life time of the sandbox in seconds, default is 3600.
	MaxLifeSeconds int32 `json:"maxLifeSeconds"`
	// The project id to use for the sandbox. Use default if not provided.
	ProjectId *string `json:"projectId,omitempty"`
}
