// Code generated by OpenAPI Generator. DO NOT EDIT.
//
// lybic
//
// No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
//
// API version: 0.6.3
// Generated by: OpenAPI Generator (https://openapi-generator.tech)
//

package lybic

import (
	"encoding/json"
	"fmt"
)

// ComputerUseActionResponseDtoActionsOneOf struct for ComputerUseActionResponseDtoActionsOneOf
type ComputerUseActionResponseDtoActionsOneOf struct {
	ComputerUseActionResponseDtoActionsOneOfInterface interface{}
}

func (s ComputerUseActionResponseDtoActionsOneOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(s.ComputerUseActionResponseDtoActionsOneOfInterface)
}

func (s *ComputerUseActionResponseDtoActionsOneOf) UnmarshalJSON(src []byte) error {
	return fmt.Errorf("no oneOf model could be deserialized from payload: %s", string(src))
}

type NullableComputerUseActionResponseDtoActionsOneOf struct {
	value *ComputerUseActionResponseDtoActionsOneOf
	isSet bool
}

func (v NullableComputerUseActionResponseDtoActionsOneOf) Get() *ComputerUseActionResponseDtoActionsOneOf {
	return v.value
}

func (v *NullableComputerUseActionResponseDtoActionsOneOf) Set(val *ComputerUseActionResponseDtoActionsOneOf) {
	v.value = val
	v.isSet = true
}

func (v NullableComputerUseActionResponseDtoActionsOneOf) IsSet() bool {
	return v.isSet
}

func (v *NullableComputerUseActionResponseDtoActionsOneOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComputerUseActionResponseDtoActionsOneOf(val *ComputerUseActionResponseDtoActionsOneOf) *NullableComputerUseActionResponseDtoActionsOneOf {
	return &NullableComputerUseActionResponseDtoActionsOneOf{value: val, isSet: true}
}

func (v NullableComputerUseActionResponseDtoActionsOneOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComputerUseActionResponseDtoActionsOneOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
