// Code generated by OpenAPI Generator. DO NOT EDIT.
//
// lybic
//
// No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
//
// API version: 0.8.0
// Generated by: OpenAPI Generator (https://openapi-generator.tech)

package lybic

import (
	"time"

	"github.com/lybic/lybic-sdk-go/pkg/json"
)

// CreateSandboxResponseDto struct for CreateSandboxResponseDto
type CreateSandboxResponseDto struct {
	Id   string `json:"id"`
	Name string `json:"name"`
	// Deprecated, use `expiresAt` instead.
	ExpiredAt time.Time `json:"expiredAt"`
	ExpiresAt time.Time `json:"expiresAt"`
	CreatedAt time.Time `json:"createdAt"`
	ProjectId string    `json:"projectId"`
	ShapeName string    `json:"shapeName"`
}

// NewCreateSandboxResponseDto instantiates a new CreateSandboxResponseDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateSandboxResponseDto(id string, name string, expiredAt time.Time, expiresAt time.Time, createdAt time.Time, projectId string, shapeName string) *CreateSandboxResponseDto {
	this := CreateSandboxResponseDto{}
	this.Id = id
	this.Name = name
	this.ExpiredAt = expiredAt
	this.ExpiresAt = expiresAt
	this.CreatedAt = createdAt
	this.ProjectId = projectId
	this.ShapeName = shapeName
	return &this
}

// NewCreateSandboxResponseDtoWithDefaults instantiates a new CreateSandboxResponseDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateSandboxResponseDtoWithDefaults() *CreateSandboxResponseDto {
	this := CreateSandboxResponseDto{}
	return &this
}

// GetId returns the Id field value
func (o *CreateSandboxResponseDto) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CreateSandboxResponseDto) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CreateSandboxResponseDto) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *CreateSandboxResponseDto) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateSandboxResponseDto) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateSandboxResponseDto) SetName(v string) {
	o.Name = v
}

// GetExpiredAt returns the ExpiredAt field value
func (o *CreateSandboxResponseDto) GetExpiredAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ExpiredAt
}

// GetExpiredAtOk returns a tuple with the ExpiredAt field value
// and a boolean to check if the value has been set.
func (o *CreateSandboxResponseDto) GetExpiredAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiredAt, true
}

// SetExpiredAt sets field value
func (o *CreateSandboxResponseDto) SetExpiredAt(v time.Time) {
	o.ExpiredAt = v
}

// GetExpiresAt returns the ExpiresAt field value
func (o *CreateSandboxResponseDto) GetExpiresAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value
// and a boolean to check if the value has been set.
func (o *CreateSandboxResponseDto) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiresAt, true
}

// SetExpiresAt sets field value
func (o *CreateSandboxResponseDto) SetExpiresAt(v time.Time) {
	o.ExpiresAt = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *CreateSandboxResponseDto) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *CreateSandboxResponseDto) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *CreateSandboxResponseDto) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetProjectId returns the ProjectId field value
func (o *CreateSandboxResponseDto) GetProjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *CreateSandboxResponseDto) GetProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *CreateSandboxResponseDto) SetProjectId(v string) {
	o.ProjectId = v
}

// GetShapeName returns the ShapeName field value
func (o *CreateSandboxResponseDto) GetShapeName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ShapeName
}

// GetShapeNameOk returns a tuple with the ShapeName field value
// and a boolean to check if the value has been set.
func (o *CreateSandboxResponseDto) GetShapeNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ShapeName, true
}

// SetShapeName sets field value
func (o *CreateSandboxResponseDto) SetShapeName(v string) {
	o.ShapeName = v
}

func (o CreateSandboxResponseDto) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["expiredAt"] = o.ExpiredAt
	}
	if true {
		toSerialize["expiresAt"] = o.ExpiresAt
	}
	if true {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if true {
		toSerialize["projectId"] = o.ProjectId
	}
	if true {
		toSerialize["shapeName"] = o.ShapeName
	}
	return json.Marshal(toSerialize)
}

type NullableCreateSandboxResponseDto struct {
	value *CreateSandboxResponseDto
	isSet bool
}

func (v NullableCreateSandboxResponseDto) Get() *CreateSandboxResponseDto {
	return v.value
}

func (v *NullableCreateSandboxResponseDto) Set(val *CreateSandboxResponseDto) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateSandboxResponseDto) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateSandboxResponseDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateSandboxResponseDto(val *CreateSandboxResponseDto) *NullableCreateSandboxResponseDto {
	return &NullableCreateSandboxResponseDto{value: val, isSet: true}
}

func (v NullableCreateSandboxResponseDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateSandboxResponseDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
