// Code generated by OpenAPI Generator. DO NOT EDIT.
//
// lybic
//
// No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
//
// API version: 0.6.3
// Generated by: OpenAPI Generator (https://openapi-generator.tech)
//

package lybic

import (
	"github.com/lybic/lybic-sdk-go/pkg/json"
)

// McpServerResponseDtoPolicy struct for McpServerResponseDtoPolicy
type McpServerResponseDtoPolicy struct {
	// The maximum lifetime of a sandbox.
	SandboxMaxLifetimeSeconds *float32 `json:"sandboxMaxLifetimeSeconds,omitempty"`
	// The maximum idle time of a sandbox.
	SandboxMaxIdleTimeSeconds *float32 `json:"sandboxMaxIdleTimeSeconds,omitempty"`
	// Whether to create a new sandbox automatically when old sandbox is deleted. If not, new sandboxes will be created when calling computer use tools.
	SandboxAutoCreation *bool `json:"sandboxAutoCreation,omitempty"`
	// Whether to expose recreate tool to LLMs.
	SandboxExposeRecreateTool *bool `json:"sandboxExposeRecreateTool,omitempty"`
	// Whether to expose restart tool to LLMs.
	SandboxExposeRestartTool *bool `json:"sandboxExposeRestartTool,omitempty"`
	// Whether to expose delete tool to LLMs.
	SandboxExposeDeleteTool *bool `json:"sandboxExposeDeleteTool,omitempty"`
}

// NewMcpServerResponseDtoPolicy instantiates a new McpServerResponseDtoPolicy object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMcpServerResponseDtoPolicy() *McpServerResponseDtoPolicy {
	this := McpServerResponseDtoPolicy{}
	var sandboxMaxLifetimeSeconds float32 = 3600
	this.SandboxMaxLifetimeSeconds = &sandboxMaxLifetimeSeconds
	var sandboxMaxIdleTimeSeconds float32 = 3600
	this.SandboxMaxIdleTimeSeconds = &sandboxMaxIdleTimeSeconds
	var sandboxAutoCreation = false
	this.SandboxAutoCreation = &sandboxAutoCreation
	var sandboxExposeRecreateTool = false
	this.SandboxExposeRecreateTool = &sandboxExposeRecreateTool
	var sandboxExposeRestartTool = false
	this.SandboxExposeRestartTool = &sandboxExposeRestartTool
	var sandboxExposeDeleteTool = false
	this.SandboxExposeDeleteTool = &sandboxExposeDeleteTool
	return &this
}

// NewMcpServerResponseDtoPolicyWithDefaults instantiates a new McpServerResponseDtoPolicy object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMcpServerResponseDtoPolicyWithDefaults() *McpServerResponseDtoPolicy {
	this := McpServerResponseDtoPolicy{}
	var sandboxMaxLifetimeSeconds float32 = 3600
	this.SandboxMaxLifetimeSeconds = &sandboxMaxLifetimeSeconds
	var sandboxMaxIdleTimeSeconds float32 = 3600
	this.SandboxMaxIdleTimeSeconds = &sandboxMaxIdleTimeSeconds
	var sandboxAutoCreation = false
	this.SandboxAutoCreation = &sandboxAutoCreation
	var sandboxExposeRecreateTool = false
	this.SandboxExposeRecreateTool = &sandboxExposeRecreateTool
	var sandboxExposeRestartTool = false
	this.SandboxExposeRestartTool = &sandboxExposeRestartTool
	var sandboxExposeDeleteTool = false
	this.SandboxExposeDeleteTool = &sandboxExposeDeleteTool
	return &this
}

// GetSandboxMaxLifetimeSeconds returns the SandboxMaxLifetimeSeconds field value if set, zero value otherwise.
func (o *McpServerResponseDtoPolicy) GetSandboxMaxLifetimeSeconds() float32 {
	if o == nil || o.SandboxMaxLifetimeSeconds == nil {
		var ret float32
		return ret
	}
	return *o.SandboxMaxLifetimeSeconds
}

// GetSandboxMaxLifetimeSecondsOk returns a tuple with the SandboxMaxLifetimeSeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *McpServerResponseDtoPolicy) GetSandboxMaxLifetimeSecondsOk() (*float32, bool) {
	if o == nil || o.SandboxMaxLifetimeSeconds == nil {
		return nil, false
	}
	return o.SandboxMaxLifetimeSeconds, true
}

// HasSandboxMaxLifetimeSeconds returns a boolean if a field has been set.
func (o *McpServerResponseDtoPolicy) HasSandboxMaxLifetimeSeconds() bool {
	if o != nil && o.SandboxMaxLifetimeSeconds != nil {
		return true
	}

	return false
}

// SetSandboxMaxLifetimeSeconds gets a reference to the given float32 and assigns it to the SandboxMaxLifetimeSeconds field.
func (o *McpServerResponseDtoPolicy) SetSandboxMaxLifetimeSeconds(v float32) {
	o.SandboxMaxLifetimeSeconds = &v
}

// GetSandboxMaxIdleTimeSeconds returns the SandboxMaxIdleTimeSeconds field value if set, zero value otherwise.
func (o *McpServerResponseDtoPolicy) GetSandboxMaxIdleTimeSeconds() float32 {
	if o == nil || o.SandboxMaxIdleTimeSeconds == nil {
		var ret float32
		return ret
	}
	return *o.SandboxMaxIdleTimeSeconds
}

// GetSandboxMaxIdleTimeSecondsOk returns a tuple with the SandboxMaxIdleTimeSeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *McpServerResponseDtoPolicy) GetSandboxMaxIdleTimeSecondsOk() (*float32, bool) {
	if o == nil || o.SandboxMaxIdleTimeSeconds == nil {
		return nil, false
	}
	return o.SandboxMaxIdleTimeSeconds, true
}

// HasSandboxMaxIdleTimeSeconds returns a boolean if a field has been set.
func (o *McpServerResponseDtoPolicy) HasSandboxMaxIdleTimeSeconds() bool {
	if o != nil && o.SandboxMaxIdleTimeSeconds != nil {
		return true
	}

	return false
}

// SetSandboxMaxIdleTimeSeconds gets a reference to the given float32 and assigns it to the SandboxMaxIdleTimeSeconds field.
func (o *McpServerResponseDtoPolicy) SetSandboxMaxIdleTimeSeconds(v float32) {
	o.SandboxMaxIdleTimeSeconds = &v
}

// GetSandboxAutoCreation returns the SandboxAutoCreation field value if set, zero value otherwise.
func (o *McpServerResponseDtoPolicy) GetSandboxAutoCreation() bool {
	if o == nil || o.SandboxAutoCreation == nil {
		var ret bool
		return ret
	}
	return *o.SandboxAutoCreation
}

// GetSandboxAutoCreationOk returns a tuple with the SandboxAutoCreation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *McpServerResponseDtoPolicy) GetSandboxAutoCreationOk() (*bool, bool) {
	if o == nil || o.SandboxAutoCreation == nil {
		return nil, false
	}
	return o.SandboxAutoCreation, true
}

// HasSandboxAutoCreation returns a boolean if a field has been set.
func (o *McpServerResponseDtoPolicy) HasSandboxAutoCreation() bool {
	if o != nil && o.SandboxAutoCreation != nil {
		return true
	}

	return false
}

// SetSandboxAutoCreation gets a reference to the given bool and assigns it to the SandboxAutoCreation field.
func (o *McpServerResponseDtoPolicy) SetSandboxAutoCreation(v bool) {
	o.SandboxAutoCreation = &v
}

// GetSandboxExposeRecreateTool returns the SandboxExposeRecreateTool field value if set, zero value otherwise.
func (o *McpServerResponseDtoPolicy) GetSandboxExposeRecreateTool() bool {
	if o == nil || o.SandboxExposeRecreateTool == nil {
		var ret bool
		return ret
	}
	return *o.SandboxExposeRecreateTool
}

// GetSandboxExposeRecreateToolOk returns a tuple with the SandboxExposeRecreateTool field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *McpServerResponseDtoPolicy) GetSandboxExposeRecreateToolOk() (*bool, bool) {
	if o == nil || o.SandboxExposeRecreateTool == nil {
		return nil, false
	}
	return o.SandboxExposeRecreateTool, true
}

// HasSandboxExposeRecreateTool returns a boolean if a field has been set.
func (o *McpServerResponseDtoPolicy) HasSandboxExposeRecreateTool() bool {
	if o != nil && o.SandboxExposeRecreateTool != nil {
		return true
	}

	return false
}

// SetSandboxExposeRecreateTool gets a reference to the given bool and assigns it to the SandboxExposeRecreateTool field.
func (o *McpServerResponseDtoPolicy) SetSandboxExposeRecreateTool(v bool) {
	o.SandboxExposeRecreateTool = &v
}

// GetSandboxExposeRestartTool returns the SandboxExposeRestartTool field value if set, zero value otherwise.
func (o *McpServerResponseDtoPolicy) GetSandboxExposeRestartTool() bool {
	if o == nil || o.SandboxExposeRestartTool == nil {
		var ret bool
		return ret
	}
	return *o.SandboxExposeRestartTool
}

// GetSandboxExposeRestartToolOk returns a tuple with the SandboxExposeRestartTool field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *McpServerResponseDtoPolicy) GetSandboxExposeRestartToolOk() (*bool, bool) {
	if o == nil || o.SandboxExposeRestartTool == nil {
		return nil, false
	}
	return o.SandboxExposeRestartTool, true
}

// HasSandboxExposeRestartTool returns a boolean if a field has been set.
func (o *McpServerResponseDtoPolicy) HasSandboxExposeRestartTool() bool {
	if o != nil && o.SandboxExposeRestartTool != nil {
		return true
	}

	return false
}

// SetSandboxExposeRestartTool gets a reference to the given bool and assigns it to the SandboxExposeRestartTool field.
func (o *McpServerResponseDtoPolicy) SetSandboxExposeRestartTool(v bool) {
	o.SandboxExposeRestartTool = &v
}

// GetSandboxExposeDeleteTool returns the SandboxExposeDeleteTool field value if set, zero value otherwise.
func (o *McpServerResponseDtoPolicy) GetSandboxExposeDeleteTool() bool {
	if o == nil || o.SandboxExposeDeleteTool == nil {
		var ret bool
		return ret
	}
	return *o.SandboxExposeDeleteTool
}

// GetSandboxExposeDeleteToolOk returns a tuple with the SandboxExposeDeleteTool field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *McpServerResponseDtoPolicy) GetSandboxExposeDeleteToolOk() (*bool, bool) {
	if o == nil || o.SandboxExposeDeleteTool == nil {
		return nil, false
	}
	return o.SandboxExposeDeleteTool, true
}

// HasSandboxExposeDeleteTool returns a boolean if a field has been set.
func (o *McpServerResponseDtoPolicy) HasSandboxExposeDeleteTool() bool {
	if o != nil && o.SandboxExposeDeleteTool != nil {
		return true
	}

	return false
}

// SetSandboxExposeDeleteTool gets a reference to the given bool and assigns it to the SandboxExposeDeleteTool field.
func (o *McpServerResponseDtoPolicy) SetSandboxExposeDeleteTool(v bool) {
	o.SandboxExposeDeleteTool = &v
}

func (o McpServerResponseDtoPolicy) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.SandboxMaxLifetimeSeconds != nil {
		toSerialize["sandboxMaxLifetimeSeconds"] = o.SandboxMaxLifetimeSeconds
	}
	if o.SandboxMaxIdleTimeSeconds != nil {
		toSerialize["sandboxMaxIdleTimeSeconds"] = o.SandboxMaxIdleTimeSeconds
	}
	if o.SandboxAutoCreation != nil {
		toSerialize["sandboxAutoCreation"] = o.SandboxAutoCreation
	}
	if o.SandboxExposeRecreateTool != nil {
		toSerialize["sandboxExposeRecreateTool"] = o.SandboxExposeRecreateTool
	}
	if o.SandboxExposeRestartTool != nil {
		toSerialize["sandboxExposeRestartTool"] = o.SandboxExposeRestartTool
	}
	if o.SandboxExposeDeleteTool != nil {
		toSerialize["sandboxExposeDeleteTool"] = o.SandboxExposeDeleteTool
	}
	return json.Marshal(toSerialize)
}

type NullableMcpServerResponseDtoPolicy struct {
	value *McpServerResponseDtoPolicy
	isSet bool
}

func (v NullableMcpServerResponseDtoPolicy) Get() *McpServerResponseDtoPolicy {
	return v.value
}

func (v *NullableMcpServerResponseDtoPolicy) Set(val *McpServerResponseDtoPolicy) {
	v.value = val
	v.isSet = true
}

func (v NullableMcpServerResponseDtoPolicy) IsSet() bool {
	return v.isSet
}

func (v *NullableMcpServerResponseDtoPolicy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMcpServerResponseDtoPolicy(val *McpServerResponseDtoPolicy) *NullableMcpServerResponseDtoPolicy {
	return &NullableMcpServerResponseDtoPolicy{value: val, isSet: true}
}

func (v NullableMcpServerResponseDtoPolicy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMcpServerResponseDtoPolicy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
