/*
 * Lybic core API
 *
 * Lybic core API
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package lybic
// SandboxActionResponseDtoCursorPosition struct for SandboxActionResponseDtoCursorPosition
type SandboxActionResponseDtoCursorPosition struct {
	// The x position of the cursor.
	X float32 `json:"x"`
	// The y position of the cursor.
	Y float32 `json:"y"`
	// The width of the screen.
	ScreenWidth float32 `json:"screenWidth"`
	// The height of the screen.
	ScreenHeight float32 `json:"screenHeight"`
	// The index of the screen.
	ScreenIndex float32 `json:"screenIndex"`
}
