/*
 * Lybic core API
 *
 * Lybic core API
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package lybic

// CreateSandboxFromImageResponseDto struct for CreateSandboxFromImageResponseDto
type CreateSandboxFromImageResponseDto struct {
	Sandbox CreateSandboxResponseDto `json:"sandbox"`
	BookId  string                   `json:"bookId"`
}
