/*
 * Lybic core API
 *
 * Lybic core API
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package lybic

// SandboxShellStreamEvent represents an event from the shell stream (SSE)
type SandboxShellStreamEvent struct {
	// Type of the event: stdout, stderr, waiting, timeout, end
	Type string
	// Data content (base64 decoded for stdout/stderr/timeout, empty for waiting/end)
	Data string
}
