/*
 * Lybic core API
 *
 * Lybic core API
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package lybic

// HttpMappingResponseDto struct for HttpMappingResponseDto
type HttpMappingResponseDto struct {
	// Assigned domain for the HTTP mapping
	Domain string `json:"domain"`
	// Target TCP endpoint, e.g. 127.0.0.1:3000
	TargetEndpoint string `json:"targetEndpoint"`
	// Access token for the HTTP mapping
	AccessToken string `json:"accessToken"`
}

type CreateHttpMappingResponseDto = HttpMappingResponseDto
type GetHttpMappingResponseDto = HttpMappingResponseDto
