/*
 * Lybic core API
 *
 * Lybic core API
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package lybic

// SandboxShellCommandStreamCreateRequestDto struct for SandboxShellCommandStreamCreateRequestDto
type SandboxShellCommandStreamCreateRequestDto struct {
	// The command to execute in the shell.
	Command string `json:"command"`
	// Whether to use a TTY for the shell session.
	UseTty bool `json:"useTty,omitempty"`
	// Optional timeout for the shell session in seconds.
	TimeoutSeconds *int32 `json:"timeoutSeconds,omitempty"`
	// Optional working directory for the shell session.
	WorkingDirectory *string `json:"workingDirectory,omitempty"`
	// Number of rows for TTY (if useTty is true).
	TtyRows *int32 `json:"ttyRows,omitempty"`
	// Number of columns for TTY (if useTty is true).
	TtyCols *int32 `json:"ttyCols,omitempty"`
}
