/*
 * Lybic core API
 *
 * Lybic core API
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package lybic

// SandboxProcessRequestDto struct for SandboxProcessRequestDto
type SandboxProcessRequestDto struct {
	// Executable path
	Executable string `json:"executable"`
	// Arguments
	Args []string `json:"args,omitempty"`
	// Working directory
	WorkingDirectory string `json:"workingDirectory,omitempty"`
	// Optional stdin as base64-encoded bytes
	StdinBase64 string `json:"stdinBase64,omitempty"`
}
