// Code generated by OpenAPI Generator. DO NOT EDIT.
//
// lybic
//
// No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
//
// API version: 0.6.3
// Generated by: OpenAPI Generator (https://openapi-generator.tech)
//

package lybic

import (
	"encoding/json"
)

// CreateProjectDto struct for CreateProjectDto
type CreateProjectDto struct {
	// Name of the project.
	Name string `json:"name"`
}

// NewCreateProjectDto instantiates a new CreateProjectDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateProjectDto(name string) *CreateProjectDto {
	this := CreateProjectDto{}
	this.Name = name
	return &this
}

// NewCreateProjectDtoWithDefaults instantiates a new CreateProjectDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateProjectDtoWithDefaults() *CreateProjectDto {
	this := CreateProjectDto{}
	return &this
}

// GetName returns the Name field value
func (o *CreateProjectDto) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateProjectDto) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateProjectDto) SetName(v string) {
	o.Name = v
}

func (o CreateProjectDto) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableCreateProjectDto struct {
	value *CreateProjectDto
	isSet bool
}

func (v NullableCreateProjectDto) Get() *CreateProjectDto {
	return v.value
}

func (v *NullableCreateProjectDto) Set(val *CreateProjectDto) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateProjectDto) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateProjectDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateProjectDto(val *CreateProjectDto) *NullableCreateProjectDto {
	return &NullableCreateProjectDto{value: val, isSet: true}
}

func (v NullableCreateProjectDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateProjectDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
