// Code generated by OpenAPI Generator. DO NOT EDIT.
//
// lybic
//
// No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
//
// API version: 0.8.0
// Generated by: OpenAPI Generator (https://openapi-generator.tech)
//

package lybic

import (
	"github.com/lybic/lybic-sdk-go/pkg/json"
)

// SandboxActionResponseDto struct for SandboxActionResponseDto
type SandboxActionResponseDto struct {
	// The screenshot of the sandbox after the action is executed.
	ScreenShot     *string                                 `json:"screenShot,omitempty"`
	CursorPosition *SandboxActionResponseDtoCursorPosition `json:"cursorPosition,omitempty"`
	ActionResult   *string                                 `json:"actionResult,omitempty"`
}

// NewSandboxActionResponseDto instantiates a new SandboxActionResponseDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSandboxActionResponseDto() *SandboxActionResponseDto {
	this := SandboxActionResponseDto{}
	return &this
}

// NewSandboxActionResponseDtoWithDefaults instantiates a new SandboxActionResponseDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSandboxActionResponseDtoWithDefaults() *SandboxActionResponseDto {
	this := SandboxActionResponseDto{}
	return &this
}

// GetScreenShot returns the ScreenShot field value if set, zero value otherwise.
func (o *SandboxActionResponseDto) GetScreenShot() string {
	if o == nil || o.ScreenShot == nil {
		var ret string
		return ret
	}
	return *o.ScreenShot
}

// GetScreenShotOk returns a tuple with the ScreenShot field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SandboxActionResponseDto) GetScreenShotOk() (*string, bool) {
	if o == nil || o.ScreenShot == nil {
		return nil, false
	}
	return o.ScreenShot, true
}

// HasScreenShot returns a boolean if a field has been set.
func (o *SandboxActionResponseDto) HasScreenShot() bool {
	if o != nil && o.ScreenShot != nil {
		return true
	}

	return false
}

// SetScreenShot gets a reference to the given string and assigns it to the ScreenShot field.
func (o *SandboxActionResponseDto) SetScreenShot(v string) {
	o.ScreenShot = &v
}

// GetCursorPosition returns the CursorPosition field value if set, zero value otherwise.
func (o *SandboxActionResponseDto) GetCursorPosition() SandboxActionResponseDtoCursorPosition {
	if o == nil || o.CursorPosition == nil {
		var ret SandboxActionResponseDtoCursorPosition
		return ret
	}
	return *o.CursorPosition
}

// GetCursorPositionOk returns a tuple with the CursorPosition field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SandboxActionResponseDto) GetCursorPositionOk() (*SandboxActionResponseDtoCursorPosition, bool) {
	if o == nil || o.CursorPosition == nil {
		return nil, false
	}
	return o.CursorPosition, true
}

// HasCursorPosition returns a boolean if a field has been set.
func (o *SandboxActionResponseDto) HasCursorPosition() bool {
	if o != nil && o.CursorPosition != nil {
		return true
	}

	return false
}

// SetCursorPosition gets a reference to the given SandboxActionResponseDtoCursorPosition and assigns it to the CursorPosition field.
func (o *SandboxActionResponseDto) SetCursorPosition(v SandboxActionResponseDtoCursorPosition) {
	o.CursorPosition = &v
}

// GetActionResult returns the ActionResult field value if set, zero value otherwise.
func (o *SandboxActionResponseDto) GetActionResult() string {
	if o == nil || o.ActionResult == nil {
		var ret string
		return ret
	}
	return *o.ActionResult
}

// GetActionResultOk returns a tuple with the ActionResult field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SandboxActionResponseDto) GetActionResultOk() (*string, bool) {
	if o == nil || o.ActionResult == nil {
		return nil, false
	}
	return o.ActionResult, true
}

// HasActionResult returns a boolean if a field has been set.
func (o *SandboxActionResponseDto) HasActionResult() bool {
	if o != nil && o.ActionResult != nil {
		return true
	}

	return false
}

// SetActionResult gets a reference to the given string and assigns it to the ActionResult field.
func (o *SandboxActionResponseDto) SetActionResult(v string) {
	o.ActionResult = &v
}

func (o SandboxActionResponseDto) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ScreenShot != nil {
		toSerialize["screenShot"] = o.ScreenShot
	}
	if o.CursorPosition != nil {
		toSerialize["cursorPosition"] = o.CursorPosition
	}
	if o.ActionResult != nil {
		toSerialize["actionResult"] = o.ActionResult
	}
	return json.Marshal(toSerialize)
}

type NullableSandboxActionResponseDto struct {
	value *SandboxActionResponseDto
	isSet bool
}

func (v NullableSandboxActionResponseDto) Get() *SandboxActionResponseDto {
	return v.value
}

func (v *NullableSandboxActionResponseDto) Set(val *SandboxActionResponseDto) {
	v.value = val
	v.isSet = true
}

func (v NullableSandboxActionResponseDto) IsSet() bool {
	return v.isSet
}

func (v *NullableSandboxActionResponseDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSandboxActionResponseDto(val *SandboxActionResponseDto) *NullableSandboxActionResponseDto {
	return &NullableSandboxActionResponseDto{value: val, isSet: true}
}

func (v NullableSandboxActionResponseDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSandboxActionResponseDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
