/*
 * Lybic core API
 *
 * Lybic core API
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package lybic

import "github.com/lybic/lybic-sdk-go/pkg/json"

// SandboxShellCommandReadResponseDto struct for SandboxShellCommandReadResponseDto
type SandboxShellCommandReadResponseDto struct {
	// Accumulated output parts from the shell session.
	Outputs []SandboxShellCommandOutput `json:"outputs"`
	// Whether the shell session is still running.
	IsRunning bool `json:"isRunning"`
}

// sandboxShellOutputItem is used internally to unwrap the "output" envelope in JSON.
type sandboxShellOutputItem struct {
	Output SandboxShellCommandOutput `json:"output"`
}

// UnmarshalJSON unwraps each element's "output" envelope before populating Output.
func (r *SandboxShellCommandReadResponseDto) UnmarshalJSON(data []byte) error {
	type alias struct {
		Output    []sandboxShellOutputItem `json:"outputs"`
		IsRunning bool                     `json:"isRunning"`
	}
	var tmp alias
	if err := json.Unmarshal(data, &tmp); err != nil {
		return err
	}
	r.IsRunning = tmp.IsRunning
	r.Outputs = make([]SandboxShellCommandOutput, len(tmp.Output))
	for i, item := range tmp.Output {
		r.Outputs[i] = item.Output
	}
	return nil
}

// SandboxShellCommandOutput represents a discriminated union for shell output
type SandboxShellCommandOutput struct {
	// OneofKind identifies which type of output this is
	OneofKind string `json:"oneofKind"`
	// Standard output from the shell session (when oneofKind is "stdout")
	Stdout *string `json:"stdout,omitempty"`
	// Standard error output from the shell session (when oneofKind is "stderr")
	Stderr *string `json:"stderr,omitempty"`
	// Indicates a prompt waiting state (when oneofKind is "waiting")
	Waiting *bool `json:"waiting,omitempty"`
}
