/*
 * Lybic core API
 *
 * Lybic core API
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package lybic

// CreateSandboxDto struct for CreateSandboxDto
type CreateSandboxDto struct {
	// The name of the sandbox.
	Name string `json:"name,omitempty"`
	// The maximum life time of the sandbox in seconds. Default is 1 hour, max is 1 day.
	MaxLifeSeconds float32 `json:"maxLifeSeconds,omitempty"`
	// The project id to use for the sandbox. Use default if not provided.
	ProjectId string `json:"projectId,omitempty"`
	// Specs and datacenter of the sandbox.
	Shape string `json:"shape"`
}
