/*
 * Lybic core API
 *
 * Lybic core API
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package lybic

// CreateHttpMappingDto struct for CreateHttpMappingDto
type CreateHttpMappingDto struct {
	// Target TCP endpoint, e.g., 127.0.0.1:3000
	TargetEndpoint string `json:"targetEndpoint"`
}
