// Code generated by OpenAPI Generator. DO NOT EDIT.
//
// lybic
//
// No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
//
// API version: 0.6.3
// Generated by: OpenAPI Generator (https://openapi-generator.tech)
//

package lybic

import (
	"encoding/json"
	"fmt"
)

// ComputerUseActionDtoActionOneOf struct for ComputerUseActionDtoActionOneOf
type ComputerUseActionDtoActionOneOf struct {
	ComputerUseActionDtoActionOneOfInterface interface{}
}

func (s ComputerUseActionDtoActionOneOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(s.ComputerUseActionDtoActionOneOfInterface)
}

func (s *ComputerUseActionDtoActionOneOf) UnmarshalJSON(src []byte) error {
	return fmt.Errorf("no oneOf model could be deserialized from payload: %s", string(src))
}

type NullableComputerUseActionDtoActionOneOf struct {
	value *ComputerUseActionDtoActionOneOf
	isSet bool
}

func (v NullableComputerUseActionDtoActionOneOf) Get() *ComputerUseActionDtoActionOneOf {
	return v.value
}

func (v *NullableComputerUseActionDtoActionOneOf) Set(val *ComputerUseActionDtoActionOneOf) {
	v.value = val
	v.isSet = true
}

func (v NullableComputerUseActionDtoActionOneOf) IsSet() bool {
	return v.isSet
}

func (v *NullableComputerUseActionDtoActionOneOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComputerUseActionDtoActionOneOf(val *ComputerUseActionDtoActionOneOf) *NullableComputerUseActionDtoActionOneOf {
	return &NullableComputerUseActionDtoActionOneOf{value: val, isSet: true}
}

func (v NullableComputerUseActionDtoActionOneOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComputerUseActionDtoActionOneOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
