/*
 * Lybic core API
 *
 * Lybic core API
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package lybic

// GetSandboxResponseDto struct for GetSandboxResponseDto
type GetSandboxResponseDto struct {
	Sandbox        GetSandboxResponseDtoSandbox        `json:"sandbox"`
	ConnectDetails GetSandboxResponseDtoConnectDetails `json:"connectDetails"`
}
