/*
 * Lybic core API
 *
 * Lybic core API
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package lybic
import (
	"time"
)
// GetSandboxResponseDtoSandbox struct for GetSandboxResponseDtoSandbox
type GetSandboxResponseDtoSandbox struct {
	Id string `json:"id"`
	Name string `json:"name"`
	// Deprecated, use `expiresAt` instead.
	ExpiredAt time.Time `json:"expiredAt"`
	ExpiresAt time.Time `json:"expiresAt"`
	CreatedAt time.Time `json:"createdAt"`
	ProjectId string `json:"projectId"`
	ShapeName string `json:"shapeName"`
	Shape GetSandboxResponseDtoSandboxShape `json:"shape"`
}
