// Code generated by OpenAPI Generator. DO NOT EDIT.
//
// lybic
//
// No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
//
// API version: 0.8.0
// Generated by: OpenAPI Generator (https://openapi-generator.tech)

package lybic

import (
	"fmt"

	"github.com/lybic/lybic-sdk-go/pkg/json"
)

// MobileUseActionResponseDtoActionsOneOf struct for MobileUseActionResponseDtoActionsOneOf
type MobileUseActionResponseDtoActionsOneOf struct {
	MobileUseActionResponseDtoActionsOneOfInterface interface{}
}

func (s MobileUseActionResponseDtoActionsOneOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(s.MobileUseActionResponseDtoActionsOneOfInterface)
}

func (s *MobileUseActionResponseDtoActionsOneOf) UnmarshalJSON(src []byte) error {
	return fmt.Errorf("No oneOf model could be deserialized from payload: %s", string(src))
}

type NullableMobileUseActionResponseDtoActionsOneOf struct {
	value *MobileUseActionResponseDtoActionsOneOf
	isSet bool
}

func (v NullableMobileUseActionResponseDtoActionsOneOf) Get() *MobileUseActionResponseDtoActionsOneOf {
	return v.value
}

func (v *NullableMobileUseActionResponseDtoActionsOneOf) Set(val *MobileUseActionResponseDtoActionsOneOf) {
	v.value = val
	v.isSet = true
}

func (v NullableMobileUseActionResponseDtoActionsOneOf) IsSet() bool {
	return v.isSet
}

func (v *NullableMobileUseActionResponseDtoActionsOneOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMobileUseActionResponseDtoActionsOneOf(val *MobileUseActionResponseDtoActionsOneOf) *NullableMobileUseActionResponseDtoActionsOneOf {
	return &NullableMobileUseActionResponseDtoActionsOneOf{value: val, isSet: true}
}

func (v NullableMobileUseActionResponseDtoActionsOneOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMobileUseActionResponseDtoActionsOneOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
