// Code generated by OpenAPI Generator. DO NOT EDIT.
//
// lybic
//
// No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
//
// API version: 0.6.3
// Generated by: OpenAPI Generator (https://openapi-generator.tech)
//

package lybic

import (
	"encoding/json"
)

// GetSandboxResponseDtoConnectDetails struct for GetSandboxResponseDtoConnectDetails
type GetSandboxResponseDtoConnectDetails struct {
	GatewayAddresses      []GetSandboxResponseDtoConnectDetailsGatewayAddresses `json:"gatewayAddresses"`
	CertificateHashBase64 string                                                `json:"certificateHashBase64"`
	EndUserToken          string                                                `json:"endUserToken"`
	RoomId                string                                                `json:"roomId"`
}

// NewGetSandboxResponseDtoConnectDetails instantiates a new GetSandboxResponseDtoConnectDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSandboxResponseDtoConnectDetails(gatewayAddresses []GetSandboxResponseDtoConnectDetailsGatewayAddresses, certificateHashBase64 string, endUserToken string, roomId string) *GetSandboxResponseDtoConnectDetails {
	this := GetSandboxResponseDtoConnectDetails{}
	this.GatewayAddresses = gatewayAddresses
	this.CertificateHashBase64 = certificateHashBase64
	this.EndUserToken = endUserToken
	this.RoomId = roomId
	return &this
}

// NewGetSandboxResponseDtoConnectDetailsWithDefaults instantiates a new GetSandboxResponseDtoConnectDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSandboxResponseDtoConnectDetailsWithDefaults() *GetSandboxResponseDtoConnectDetails {
	this := GetSandboxResponseDtoConnectDetails{}
	return &this
}

// GetGatewayAddresses returns the GatewayAddresses field value
func (o *GetSandboxResponseDtoConnectDetails) GetGatewayAddresses() []GetSandboxResponseDtoConnectDetailsGatewayAddresses {
	if o == nil {
		var ret []GetSandboxResponseDtoConnectDetailsGatewayAddresses
		return ret
	}

	return o.GatewayAddresses
}

// GetGatewayAddressesOk returns a tuple with the GatewayAddresses field value
// and a boolean to check if the value has been set.
func (o *GetSandboxResponseDtoConnectDetails) GetGatewayAddressesOk() (*[]GetSandboxResponseDtoConnectDetailsGatewayAddresses, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GatewayAddresses, true
}

// SetGatewayAddresses sets field value
func (o *GetSandboxResponseDtoConnectDetails) SetGatewayAddresses(v []GetSandboxResponseDtoConnectDetailsGatewayAddresses) {
	o.GatewayAddresses = v
}

// GetCertificateHashBase64 returns the CertificateHashBase64 field value
func (o *GetSandboxResponseDtoConnectDetails) GetCertificateHashBase64() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CertificateHashBase64
}

// GetCertificateHashBase64Ok returns a tuple with the CertificateHashBase64 field value
// and a boolean to check if the value has been set.
func (o *GetSandboxResponseDtoConnectDetails) GetCertificateHashBase64Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CertificateHashBase64, true
}

// SetCertificateHashBase64 sets field value
func (o *GetSandboxResponseDtoConnectDetails) SetCertificateHashBase64(v string) {
	o.CertificateHashBase64 = v
}

// GetEndUserToken returns the EndUserToken field value
func (o *GetSandboxResponseDtoConnectDetails) GetEndUserToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EndUserToken
}

// GetEndUserTokenOk returns a tuple with the EndUserToken field value
// and a boolean to check if the value has been set.
func (o *GetSandboxResponseDtoConnectDetails) GetEndUserTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EndUserToken, true
}

// SetEndUserToken sets field value
func (o *GetSandboxResponseDtoConnectDetails) SetEndUserToken(v string) {
	o.EndUserToken = v
}

// GetRoomId returns the RoomId field value
func (o *GetSandboxResponseDtoConnectDetails) GetRoomId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RoomId
}

// GetRoomIdOk returns a tuple with the RoomId field value
// and a boolean to check if the value has been set.
func (o *GetSandboxResponseDtoConnectDetails) GetRoomIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RoomId, true
}

// SetRoomId sets field value
func (o *GetSandboxResponseDtoConnectDetails) SetRoomId(v string) {
	o.RoomId = v
}

func (o GetSandboxResponseDtoConnectDetails) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["gatewayAddresses"] = o.GatewayAddresses
	}
	if true {
		toSerialize["certificateHashBase64"] = o.CertificateHashBase64
	}
	if true {
		toSerialize["endUserToken"] = o.EndUserToken
	}
	if true {
		toSerialize["roomId"] = o.RoomId
	}
	return json.Marshal(toSerialize)
}

type NullableGetSandboxResponseDtoConnectDetails struct {
	value *GetSandboxResponseDtoConnectDetails
	isSet bool
}

func (v NullableGetSandboxResponseDtoConnectDetails) Get() *GetSandboxResponseDtoConnectDetails {
	return v.value
}

func (v *NullableGetSandboxResponseDtoConnectDetails) Set(val *GetSandboxResponseDtoConnectDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSandboxResponseDtoConnectDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSandboxResponseDtoConnectDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSandboxResponseDtoConnectDetails(val *GetSandboxResponseDtoConnectDetails) *NullableGetSandboxResponseDtoConnectDetails {
	return &NullableGetSandboxResponseDtoConnectDetails{value: val, isSet: true}
}

func (v NullableGetSandboxResponseDtoConnectDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSandboxResponseDtoConnectDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
