// Code generated by OpenAPI Generator. DO NOT EDIT.
//
// lybic
//
// No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
//
// API version: 0.8
// Generated by: OpenAPI Generator (https://openapi-generator.tech)
//

package lybic

import (
	"github.com/lybic/lybic-sdk-go/pkg/json"
)

// CreateMcpServerDto struct for CreateMcpServerDto
type CreateMcpServerDto struct {
	// Name of the MCP server.
	Name string `json:"name"`
	// Project to which the MCP server belongs to.
	ProjectId *string `json:"projectId,omitempty"`
	// The shape of the sandbox created by the MCP server.
	SandboxShape string `json:"sandboxShape"`
	// The maximum lifetime of a sandbox.
	SandboxMaxLifetimeSeconds *float32 `json:"sandboxMaxLifetimeSeconds,omitempty"`
	// The maximum idle time of a sandbox.
	SandboxMaxIdleTimeSeconds *float32 `json:"sandboxMaxIdleTimeSeconds,omitempty"`
	// Whether to create a new sandbox automatically when old sandbox is deleted. If not, new sandboxes will be created when calling computer use tools.
	SandboxAutoCreation *bool `json:"sandboxAutoCreation,omitempty"`
	// Whether to expose recreate tool to LLMs.
	SandboxExposeRecreateTool *bool `json:"sandboxExposeRecreateTool,omitempty"`
	// Whether to expose restart tool to LLMs.
	SandboxExposeRestartTool *bool `json:"sandboxExposeRestartTool,omitempty"`
	// Whether to expose delete tool to LLMs.
	SandboxExposeDeleteTool *bool `json:"sandboxExposeDeleteTool,omitempty"`
}

// NewCreateMcpServerDto instantiates a new CreateMcpServerDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateMcpServerDto(name string, sandboxShape string) *CreateMcpServerDto {
	this := CreateMcpServerDto{}
	this.Name = name
	this.SandboxShape = sandboxShape
	var sandboxMaxLifetimeSeconds float32 = 3600
	this.SandboxMaxLifetimeSeconds = &sandboxMaxLifetimeSeconds
	var sandboxMaxIdleTimeSeconds float32 = 3600
	this.SandboxMaxIdleTimeSeconds = &sandboxMaxIdleTimeSeconds
	var sandboxAutoCreation = false
	this.SandboxAutoCreation = &sandboxAutoCreation
	var sandboxExposeRecreateTool = false
	this.SandboxExposeRecreateTool = &sandboxExposeRecreateTool
	var sandboxExposeRestartTool = false
	this.SandboxExposeRestartTool = &sandboxExposeRestartTool
	var sandboxExposeDeleteTool = false
	this.SandboxExposeDeleteTool = &sandboxExposeDeleteTool
	return &this
}

// NewCreateMcpServerDtoWithDefaults instantiates a new CreateMcpServerDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateMcpServerDtoWithDefaults() *CreateMcpServerDto {
	this := CreateMcpServerDto{}
	var sandboxMaxLifetimeSeconds float32 = 3600
	this.SandboxMaxLifetimeSeconds = &sandboxMaxLifetimeSeconds
	var sandboxMaxIdleTimeSeconds float32 = 3600
	this.SandboxMaxIdleTimeSeconds = &sandboxMaxIdleTimeSeconds
	var sandboxAutoCreation = false
	this.SandboxAutoCreation = &sandboxAutoCreation
	var sandboxExposeRecreateTool = false
	this.SandboxExposeRecreateTool = &sandboxExposeRecreateTool
	var sandboxExposeRestartTool = false
	this.SandboxExposeRestartTool = &sandboxExposeRestartTool
	var sandboxExposeDeleteTool = false
	this.SandboxExposeDeleteTool = &sandboxExposeDeleteTool
	return &this
}

// GetName returns the Name field value
func (o *CreateMcpServerDto) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateMcpServerDto) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateMcpServerDto) SetName(v string) {
	o.Name = v
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise.
func (o *CreateMcpServerDto) GetProjectId() string {
	if o == nil || o.ProjectId == nil {
		var ret string
		return ret
	}
	return *o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateMcpServerDto) GetProjectIdOk() (*string, bool) {
	if o == nil || o.ProjectId == nil {
		return nil, false
	}
	return o.ProjectId, true
}

// HasProjectId returns a boolean if a field has been set.
func (o *CreateMcpServerDto) HasProjectId() bool {
	if o != nil && o.ProjectId != nil {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given string and assigns it to the ProjectId field.
func (o *CreateMcpServerDto) SetProjectId(v string) {
	o.ProjectId = &v
}

// GetSandboxShape returns the SandboxShape field value
func (o *CreateMcpServerDto) GetSandboxShape() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SandboxShape
}

// GetSandboxShapeOk returns a tuple with the SandboxShape field value
// and a boolean to check if the value has been set.
func (o *CreateMcpServerDto) GetSandboxShapeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SandboxShape, true
}

// SetSandboxShape sets field value
func (o *CreateMcpServerDto) SetSandboxShape(v string) {
	o.SandboxShape = v
}

// GetSandboxMaxLifetimeSeconds returns the SandboxMaxLifetimeSeconds field value if set, zero value otherwise.
func (o *CreateMcpServerDto) GetSandboxMaxLifetimeSeconds() float32 {
	if o == nil || o.SandboxMaxLifetimeSeconds == nil {
		var ret float32
		return ret
	}
	return *o.SandboxMaxLifetimeSeconds
}

// GetSandboxMaxLifetimeSecondsOk returns a tuple with the SandboxMaxLifetimeSeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateMcpServerDto) GetSandboxMaxLifetimeSecondsOk() (*float32, bool) {
	if o == nil || o.SandboxMaxLifetimeSeconds == nil {
		return nil, false
	}
	return o.SandboxMaxLifetimeSeconds, true
}

// HasSandboxMaxLifetimeSeconds returns a boolean if a field has been set.
func (o *CreateMcpServerDto) HasSandboxMaxLifetimeSeconds() bool {
	if o != nil && o.SandboxMaxLifetimeSeconds != nil {
		return true
	}

	return false
}

// SetSandboxMaxLifetimeSeconds gets a reference to the given float32 and assigns it to the SandboxMaxLifetimeSeconds field.
func (o *CreateMcpServerDto) SetSandboxMaxLifetimeSeconds(v float32) {
	o.SandboxMaxLifetimeSeconds = &v
}

// GetSandboxMaxIdleTimeSeconds returns the SandboxMaxIdleTimeSeconds field value if set, zero value otherwise.
func (o *CreateMcpServerDto) GetSandboxMaxIdleTimeSeconds() float32 {
	if o == nil || o.SandboxMaxIdleTimeSeconds == nil {
		var ret float32
		return ret
	}
	return *o.SandboxMaxIdleTimeSeconds
}

// GetSandboxMaxIdleTimeSecondsOk returns a tuple with the SandboxMaxIdleTimeSeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateMcpServerDto) GetSandboxMaxIdleTimeSecondsOk() (*float32, bool) {
	if o == nil || o.SandboxMaxIdleTimeSeconds == nil {
		return nil, false
	}
	return o.SandboxMaxIdleTimeSeconds, true
}

// HasSandboxMaxIdleTimeSeconds returns a boolean if a field has been set.
func (o *CreateMcpServerDto) HasSandboxMaxIdleTimeSeconds() bool {
	if o != nil && o.SandboxMaxIdleTimeSeconds != nil {
		return true
	}

	return false
}

// SetSandboxMaxIdleTimeSeconds gets a reference to the given float32 and assigns it to the SandboxMaxIdleTimeSeconds field.
func (o *CreateMcpServerDto) SetSandboxMaxIdleTimeSeconds(v float32) {
	o.SandboxMaxIdleTimeSeconds = &v
}

// GetSandboxAutoCreation returns the SandboxAutoCreation field value if set, zero value otherwise.
func (o *CreateMcpServerDto) GetSandboxAutoCreation() bool {
	if o == nil || o.SandboxAutoCreation == nil {
		var ret bool
		return ret
	}
	return *o.SandboxAutoCreation
}

// GetSandboxAutoCreationOk returns a tuple with the SandboxAutoCreation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateMcpServerDto) GetSandboxAutoCreationOk() (*bool, bool) {
	if o == nil || o.SandboxAutoCreation == nil {
		return nil, false
	}
	return o.SandboxAutoCreation, true
}

// HasSandboxAutoCreation returns a boolean if a field has been set.
func (o *CreateMcpServerDto) HasSandboxAutoCreation() bool {
	if o != nil && o.SandboxAutoCreation != nil {
		return true
	}

	return false
}

// SetSandboxAutoCreation gets a reference to the given bool and assigns it to the SandboxAutoCreation field.
func (o *CreateMcpServerDto) SetSandboxAutoCreation(v bool) {
	o.SandboxAutoCreation = &v
}

// GetSandboxExposeRecreateTool returns the SandboxExposeRecreateTool field value if set, zero value otherwise.
func (o *CreateMcpServerDto) GetSandboxExposeRecreateTool() bool {
	if o == nil || o.SandboxExposeRecreateTool == nil {
		var ret bool
		return ret
	}
	return *o.SandboxExposeRecreateTool
}

// GetSandboxExposeRecreateToolOk returns a tuple with the SandboxExposeRecreateTool field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateMcpServerDto) GetSandboxExposeRecreateToolOk() (*bool, bool) {
	if o == nil || o.SandboxExposeRecreateTool == nil {
		return nil, false
	}
	return o.SandboxExposeRecreateTool, true
}

// HasSandboxExposeRecreateTool returns a boolean if a field has been set.
func (o *CreateMcpServerDto) HasSandboxExposeRecreateTool() bool {
	if o != nil && o.SandboxExposeRecreateTool != nil {
		return true
	}

	return false
}

// SetSandboxExposeRecreateTool gets a reference to the given bool and assigns it to the SandboxExposeRecreateTool field.
func (o *CreateMcpServerDto) SetSandboxExposeRecreateTool(v bool) {
	o.SandboxExposeRecreateTool = &v
}

// GetSandboxExposeRestartTool returns the SandboxExposeRestartTool field value if set, zero value otherwise.
func (o *CreateMcpServerDto) GetSandboxExposeRestartTool() bool {
	if o == nil || o.SandboxExposeRestartTool == nil {
		var ret bool
		return ret
	}
	return *o.SandboxExposeRestartTool
}

// GetSandboxExposeRestartToolOk returns a tuple with the SandboxExposeRestartTool field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateMcpServerDto) GetSandboxExposeRestartToolOk() (*bool, bool) {
	if o == nil || o.SandboxExposeRestartTool == nil {
		return nil, false
	}
	return o.SandboxExposeRestartTool, true
}

// HasSandboxExposeRestartTool returns a boolean if a field has been set.
func (o *CreateMcpServerDto) HasSandboxExposeRestartTool() bool {
	if o != nil && o.SandboxExposeRestartTool != nil {
		return true
	}

	return false
}

// SetSandboxExposeRestartTool gets a reference to the given bool and assigns it to the SandboxExposeRestartTool field.
func (o *CreateMcpServerDto) SetSandboxExposeRestartTool(v bool) {
	o.SandboxExposeRestartTool = &v
}

// GetSandboxExposeDeleteTool returns the SandboxExposeDeleteTool field value if set, zero value otherwise.
func (o *CreateMcpServerDto) GetSandboxExposeDeleteTool() bool {
	if o == nil || o.SandboxExposeDeleteTool == nil {
		var ret bool
		return ret
	}
	return *o.SandboxExposeDeleteTool
}

// GetSandboxExposeDeleteToolOk returns a tuple with the SandboxExposeDeleteTool field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateMcpServerDto) GetSandboxExposeDeleteToolOk() (*bool, bool) {
	if o == nil || o.SandboxExposeDeleteTool == nil {
		return nil, false
	}
	return o.SandboxExposeDeleteTool, true
}

// HasSandboxExposeDeleteTool returns a boolean if a field has been set.
func (o *CreateMcpServerDto) HasSandboxExposeDeleteTool() bool {
	if o != nil && o.SandboxExposeDeleteTool != nil {
		return true
	}

	return false
}

// SetSandboxExposeDeleteTool gets a reference to the given bool and assigns it to the SandboxExposeDeleteTool field.
func (o *CreateMcpServerDto) SetSandboxExposeDeleteTool(v bool) {
	o.SandboxExposeDeleteTool = &v
}

func (o CreateMcpServerDto) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	if o.ProjectId != nil {
		toSerialize["projectId"] = o.ProjectId
	}
	if true {
		toSerialize["sandboxShape"] = o.SandboxShape
	}
	if o.SandboxMaxLifetimeSeconds != nil {
		toSerialize["sandboxMaxLifetimeSeconds"] = o.SandboxMaxLifetimeSeconds
	}
	if o.SandboxMaxIdleTimeSeconds != nil {
		toSerialize["sandboxMaxIdleTimeSeconds"] = o.SandboxMaxIdleTimeSeconds
	}
	if o.SandboxAutoCreation != nil {
		toSerialize["sandboxAutoCreation"] = o.SandboxAutoCreation
	}
	if o.SandboxExposeRecreateTool != nil {
		toSerialize["sandboxExposeRecreateTool"] = o.SandboxExposeRecreateTool
	}
	if o.SandboxExposeRestartTool != nil {
		toSerialize["sandboxExposeRestartTool"] = o.SandboxExposeRestartTool
	}
	if o.SandboxExposeDeleteTool != nil {
		toSerialize["sandboxExposeDeleteTool"] = o.SandboxExposeDeleteTool
	}
	return json.Marshal(toSerialize)
}

type NullableCreateMcpServerDto struct {
	value *CreateMcpServerDto
	isSet bool
}

func (v NullableCreateMcpServerDto) Get() *CreateMcpServerDto {
	return v.value
}

func (v *NullableCreateMcpServerDto) Set(val *CreateMcpServerDto) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateMcpServerDto) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateMcpServerDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateMcpServerDto(val *CreateMcpServerDto) *NullableCreateMcpServerDto {
	return &NullableCreateMcpServerDto{value: val, isSet: true}
}

func (v NullableCreateMcpServerDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateMcpServerDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
