// Code generated by OpenAPI Generator. DO NOT EDIT.
//
// lybic
//
// No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
//
// API version: 0.8.0
// Generated by: OpenAPI Generator (https://openapi-generator.tech)

package lybic

import (
	"github.com/lybic/lybic-sdk-go/pkg/json"
)

// ExecuteSandboxActionDto struct for ExecuteSandboxActionDto
type ExecuteSandboxActionDto struct {
	Action SandboxUseActionDtoActionOneOf `json:"action"`
	// Whether to include the screenshot url after action in the response
	IncludeScreenShot *bool `json:"includeScreenShot,omitempty"`
	// Whether to include the cursor position after action in the response. On some cursor-less devices, only width and height are meaningful.
	IncludeCursorPosition *bool `json:"includeCursorPosition,omitempty"`
}

// NewExecuteSandboxActionDto instantiates a new ExecuteSandboxActionDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExecuteSandboxActionDto(action SandboxUseActionDtoActionOneOf) *ExecuteSandboxActionDto {
	this := ExecuteSandboxActionDto{}
	this.Action = action
	var includeScreenShot bool = true
	this.IncludeScreenShot = &includeScreenShot
	var includeCursorPosition bool = true
	this.IncludeCursorPosition = &includeCursorPosition
	return &this
}

// NewExecuteSandboxActionDtoWithDefaults instantiates a new ExecuteSandboxActionDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExecuteSandboxActionDtoWithDefaults() *ExecuteSandboxActionDto {
	this := ExecuteSandboxActionDto{}
	var includeScreenShot bool = true
	this.IncludeScreenShot = &includeScreenShot
	var includeCursorPosition bool = true
	this.IncludeCursorPosition = &includeCursorPosition
	return &this
}

// GetAction returns the Action field value
func (o *ExecuteSandboxActionDto) GetAction() SandboxUseActionDtoActionOneOf {
	if o == nil {
		var ret SandboxUseActionDtoActionOneOf
		return ret
	}

	return o.Action
}

func (o ExecuteSandboxActionDto) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["action"] = o.Action
	}
	if o.IncludeScreenShot != nil {
		toSerialize["includeScreenShot"] = o.IncludeScreenShot
	}
	if o.IncludeCursorPosition != nil {
		toSerialize["includeCursorPosition"] = o.IncludeCursorPosition
	}
	return json.Marshal(toSerialize)
}

type NullableExecuteSandboxActionDto struct {
	value *ExecuteSandboxActionDto
	isSet bool
}

func (v NullableExecuteSandboxActionDto) Get() *ExecuteSandboxActionDto {
	return v.value
}

func (v *NullableExecuteSandboxActionDto) Set(val *ExecuteSandboxActionDto) {
	v.value = val
	v.isSet = true
}

func (v NullableExecuteSandboxActionDto) IsSet() bool {
	return v.isSet
}

func (v *NullableExecuteSandboxActionDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExecuteSandboxActionDto(val *ExecuteSandboxActionDto) *NullableExecuteSandboxActionDto {
	return &NullableExecuteSandboxActionDto{value: val, isSet: true}
}

func (v NullableExecuteSandboxActionDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExecuteSandboxActionDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
