// Code generated by OpenAPI Generator. DO NOT EDIT.
//
// lybic
//
// No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
//
// API version: 0.8.0
// Generated by: OpenAPI Generator (https://openapi-generator.tech)

package lybic

import (
	"github.com/lybic/lybic-sdk-go/pkg/json"
)

// MobileUseActionResponseDto struct for MobileUseActionResponseDto
type MobileUseActionResponseDto struct {
	Actions []MobileUseActionResponseDtoActionsOneOf `json:"actions"`
	// Unknown text that is not thoughts nor actions, commonly due to the misformat of model output
	Unknown *string `json:"unknown,omitempty"`
	// Memory that is not parsed
	Memory *string `json:"memory,omitempty"`
	// Thoughts that are not parsed
	Thoughts *string `json:"thoughts,omitempty"`
}

func (m *MobileUseActionResponseDto) UnmarshalJSON(data []byte) error {
	var temp struct {
		Actions  []json.RawMessage `json:"actions"`
		Unknown  *string           `json:"unknown,omitempty"`
		Memory   *string           `json:"memory,omitempty"`
		Thoughts *string           `json:"thoughts,omitempty"`
	}

	if err := json.Unmarshal(data, &temp); err != nil {
		return err
	}
	for _, tempAction := range temp.Actions {
		var action MobileUseActionResponseDtoActionsOneOf
		if err := json.Unmarshal(tempAction, &action); err != nil {
			return err
		}
		m.Actions = append(m.Actions, action)
	}
	m.Unknown = temp.Unknown
	m.Memory = temp.Memory
	m.Thoughts = temp.Thoughts

	return nil
}

// NewMobileUseActionResponseDto instantiates a new MobileUseActionResponseDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMobileUseActionResponseDto(actions []MobileUseActionResponseDtoActionsOneOf) *MobileUseActionResponseDto {
	this := MobileUseActionResponseDto{}
	this.Actions = actions
	return &this
}

// NewMobileUseActionResponseDtoWithDefaults instantiates a new MobileUseActionResponseDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMobileUseActionResponseDtoWithDefaults() *MobileUseActionResponseDto {
	this := MobileUseActionResponseDto{}
	return &this
}

// GetActions returns the Actions field value
func (o *MobileUseActionResponseDto) GetActions() []MobileUseActionResponseDtoActionsOneOf {
	if o == nil {
		var ret []MobileUseActionResponseDtoActionsOneOf
		return ret
	}

	return o.Actions
}

// GetActionsOk returns a tuple with the Actions field value
// and a boolean to check if the value has been set.
func (o *MobileUseActionResponseDto) GetActionsOk() (*[]MobileUseActionResponseDtoActionsOneOf, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Actions, true
}

// SetActions sets field value
func (o *MobileUseActionResponseDto) SetActions(v []MobileUseActionResponseDtoActionsOneOf) {
	o.Actions = v
}

// GetUnknown returns the Unknown field value if set, zero value otherwise.
func (o *MobileUseActionResponseDto) GetUnknown() string {
	if o == nil || o.Unknown == nil {
		var ret string
		return ret
	}
	return *o.Unknown
}

// GetUnknownOk returns a tuple with the Unknown field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MobileUseActionResponseDto) GetUnknownOk() (*string, bool) {
	if o == nil || o.Unknown == nil {
		return nil, false
	}
	return o.Unknown, true
}

// HasUnknown returns a boolean if a field has been set.
func (o *MobileUseActionResponseDto) HasUnknown() bool {
	if o != nil && o.Unknown != nil {
		return true
	}

	return false
}

// SetUnknown gets a reference to the given string and assigns it to the Unknown field.
func (o *MobileUseActionResponseDto) SetUnknown(v string) {
	o.Unknown = &v
}

// GetMemory returns the Memory field value if set, zero value otherwise.
func (o *MobileUseActionResponseDto) GetMemory() string {
	if o == nil || o.Memory == nil {
		var ret string
		return ret
	}
	return *o.Memory
}

// GetMemoryOk returns a tuple with the Memory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MobileUseActionResponseDto) GetMemoryOk() (*string, bool) {
	if o == nil || o.Memory == nil {
		return nil, false
	}
	return o.Memory, true
}

// HasMemory returns a boolean if a field has been set.
func (o *MobileUseActionResponseDto) HasMemory() bool {
	if o != nil && o.Memory != nil {
		return true
	}

	return false
}

// SetMemory gets a reference to the given string and assigns it to the Memory field.
func (o *MobileUseActionResponseDto) SetMemory(v string) {
	o.Memory = &v
}

// GetThoughts returns the Thoughts field value if set, zero value otherwise.
func (o *MobileUseActionResponseDto) GetThoughts() string {
	if o == nil || o.Thoughts == nil {
		var ret string
		return ret
	}
	return *o.Thoughts
}

// GetThoughtsOk returns a tuple with the Thoughts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MobileUseActionResponseDto) GetThoughtsOk() (*string, bool) {
	if o == nil || o.Thoughts == nil {
		return nil, false
	}
	return o.Thoughts, true
}

// HasThoughts returns a boolean if a field has been set.
func (o *MobileUseActionResponseDto) HasThoughts() bool {
	if o != nil && o.Thoughts != nil {
		return true
	}

	return false
}

// SetThoughts gets a reference to the given string and assigns it to the Thoughts field.
func (o *MobileUseActionResponseDto) SetThoughts(v string) {
	o.Thoughts = &v
}

func (o MobileUseActionResponseDto) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["actions"] = o.Actions
	}
	if o.Unknown != nil {
		toSerialize["unknown"] = o.Unknown
	}
	if o.Memory != nil {
		toSerialize["memory"] = o.Memory
	}
	if o.Thoughts != nil {
		toSerialize["thoughts"] = o.Thoughts
	}
	return json.Marshal(toSerialize)
}

type NullableMobileUseActionResponseDto struct {
	value *MobileUseActionResponseDto
	isSet bool
}

func (v NullableMobileUseActionResponseDto) Get() *MobileUseActionResponseDto {
	return v.value
}

func (v *NullableMobileUseActionResponseDto) Set(val *MobileUseActionResponseDto) {
	v.value = val
	v.isSet = true
}

func (v NullableMobileUseActionResponseDto) IsSet() bool {
	return v.isSet
}

func (v *NullableMobileUseActionResponseDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMobileUseActionResponseDto(val *MobileUseActionResponseDto) *NullableMobileUseActionResponseDto {
	return &NullableMobileUseActionResponseDto{value: val, isSet: true}
}

func (v NullableMobileUseActionResponseDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMobileUseActionResponseDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
