// Code generated by OpenAPI Generator. DO NOT EDIT.
//
// lybic
//
// No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
//
// API version: 0.6.3
// Generated by: OpenAPI Generator (https://openapi-generator.tech)

package lybic

import (
	"github.com/lybic/lybic-sdk-go/pkg/json"
)

// GetSandboxResponseDto struct for GetSandboxResponseDto
type GetSandboxResponseDto struct {
	Sandbox        GetSandboxResponseDtoSandbox        `json:"sandbox"`
	ConnectDetails GetSandboxResponseDtoConnectDetails `json:"connectDetails"`
}

// NewGetSandboxResponseDto instantiates a new GetSandboxResponseDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSandboxResponseDto(sandbox GetSandboxResponseDtoSandbox, connectDetails GetSandboxResponseDtoConnectDetails) *GetSandboxResponseDto {
	this := GetSandboxResponseDto{}
	this.Sandbox = sandbox
	this.ConnectDetails = connectDetails
	return &this
}

// NewGetSandboxResponseDtoWithDefaults instantiates a new GetSandboxResponseDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSandboxResponseDtoWithDefaults() *GetSandboxResponseDto {
	this := GetSandboxResponseDto{}
	return &this
}

// GetSandbox returns the Sandbox field value
func (o *GetSandboxResponseDto) GetSandbox() GetSandboxResponseDtoSandbox {
	if o == nil {
		var ret GetSandboxResponseDtoSandbox
		return ret
	}

	return o.Sandbox
}

// GetSandboxOk returns a tuple with the Sandbox field value
// and a boolean to check if the value has been set.
func (o *GetSandboxResponseDto) GetSandboxOk() (*GetSandboxResponseDtoSandbox, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sandbox, true
}

// SetSandbox sets field value
func (o *GetSandboxResponseDto) SetSandbox(v GetSandboxResponseDtoSandbox) {
	o.Sandbox = v
}

// GetConnectDetails returns the ConnectDetails field value
func (o *GetSandboxResponseDto) GetConnectDetails() GetSandboxResponseDtoConnectDetails {
	if o == nil {
		var ret GetSandboxResponseDtoConnectDetails
		return ret
	}

	return o.ConnectDetails
}

// GetConnectDetailsOk returns a tuple with the ConnectDetails field value
// and a boolean to check if the value has been set.
func (o *GetSandboxResponseDto) GetConnectDetailsOk() (*GetSandboxResponseDtoConnectDetails, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConnectDetails, true
}

// SetConnectDetails sets field value
func (o *GetSandboxResponseDto) SetConnectDetails(v GetSandboxResponseDtoConnectDetails) {
	o.ConnectDetails = v
}

func (o GetSandboxResponseDto) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["sandbox"] = o.Sandbox
	}
	if true {
		toSerialize["connectDetails"] = o.ConnectDetails
	}
	return json.Marshal(toSerialize)
}

type NullableGetSandboxResponseDto struct {
	value *GetSandboxResponseDto
	isSet bool
}

func (v NullableGetSandboxResponseDto) Get() *GetSandboxResponseDto {
	return v.value
}

func (v *NullableGetSandboxResponseDto) Set(val *GetSandboxResponseDto) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSandboxResponseDto) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSandboxResponseDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSandboxResponseDto(val *GetSandboxResponseDto) *NullableGetSandboxResponseDto {
	return &NullableGetSandboxResponseDto{value: val, isSet: true}
}

func (v NullableGetSandboxResponseDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSandboxResponseDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
