/*
 * Lybic core API
 *
 * Lybic core API
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package lybic

import (
	"time"
)

// MachineImagesResponseDto struct for MachineImagesResponseDto
type MachineImagesResponseDto struct {
	Images []MachineImagesResponseDtoImages `json:"images"`
	Quota  MachineImagesResponseDtoQuota    `json:"quota"`
}

// MachineImagesResponseDtoImages struct for MachineImagesResponseDtoImages
type MachineImagesResponseDtoImages struct {
	Id          string    `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	CreatedAt   time.Time `json:"createdAt"`
	ShapeName   string    `json:"shapeName"`
	Status      string    `json:"status"`
}

// MachineImagesResponseDtoQuota struct for MachineImagesResponseDtoQuota
type MachineImagesResponseDtoQuota struct {
	Used  int32 `json:"used"`
	Limit int32 `json:"limit"`
}
