/*
 * Lybic core API
 *
 * Lybic core API
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package lybic

// SandboxShellCommandWriteRequestDto struct for SandboxShellCommandWriteRequestDto
type SandboxShellCommandWriteRequestDto struct {
	// The input data to write to the shell session.
	Data string `json:"data"`
}
