// Code generated by OpenAPI Generator. DO NOT EDIT.
//
// lybic
//
// No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
//
// API version: 0.8.0
// Generated by: OpenAPI Generator (https://openapi-generator.tech)

package lybic

import (
	"github.com/lybic/lybic-sdk-go/pkg/json"
)

// ParseTextRequestDto struct for ParseTextRequestDto
type ParseTextRequestDto struct {
	// The text content to parse
	TextContent string `json:"textContent"`
}

// NewParseTextRequestDto instantiates a new ParseTextRequestDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewParseTextRequestDto(textContent string) *ParseTextRequestDto {
	this := ParseTextRequestDto{}
	this.TextContent = textContent
	return &this
}

// NewParseTextRequestDtoWithDefaults instantiates a new ParseTextRequestDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewParseTextRequestDtoWithDefaults() *ParseTextRequestDto {
	this := ParseTextRequestDto{}
	return &this
}

// GetTextContent returns the TextContent field value
func (o *ParseTextRequestDto) GetTextContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TextContent
}

// GetTextContentOk returns a tuple with the TextContent field value
// and a boolean to check if the value has been set.
func (o *ParseTextRequestDto) GetTextContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TextContent, true
}

// SetTextContent sets field value
func (o *ParseTextRequestDto) SetTextContent(v string) {
	o.TextContent = v
}

func (o ParseTextRequestDto) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["textContent"] = o.TextContent
	}
	return json.Marshal(toSerialize)
}

type NullableParseTextRequestDto struct {
	value *ParseTextRequestDto
	isSet bool
}

func (v NullableParseTextRequestDto) Get() *ParseTextRequestDto {
	return v.value
}

func (v *NullableParseTextRequestDto) Set(val *ParseTextRequestDto) {
	v.value = val
	v.isSet = true
}

func (v NullableParseTextRequestDto) IsSet() bool {
	return v.isSet
}

func (v *NullableParseTextRequestDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableParseTextRequestDto(val *ParseTextRequestDto) *NullableParseTextRequestDto {
	return &NullableParseTextRequestDto{value: val, isSet: true}
}

func (v NullableParseTextRequestDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableParseTextRequestDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
