// Code generated by OpenAPI Generator. DO NOT EDIT.
//
// lybic
//
// No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
//
// API version: 0.8.0
// Generated by: OpenAPI Generator (https://openapi-generator.tech)

package lybic

import (
	"github.com/lybic/lybic-sdk-go/pkg/json"
)

// ParseRequestDto struct for ParseRequestDto
type ParseRequestDto struct {
	// The model to parse the input for
	Model string `json:"model"`
	// The text content to parse
	TextContent string `json:"textContent"`
}

// NewParseRequestDto instantiates a new ParseRequestDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewParseRequestDto(model string, textContent string) *ParseRequestDto {
	this := ParseRequestDto{}
	this.Model = model
	this.TextContent = textContent
	return &this
}

// NewParseRequestDtoWithDefaults instantiates a new ParseRequestDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewParseRequestDtoWithDefaults() *ParseRequestDto {
	this := ParseRequestDto{}
	return &this
}

// GetModel returns the Model field value
func (o *ParseRequestDto) GetModel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Model
}

// GetModelOk returns a tuple with the Model field value
// and a boolean to check if the value has been set.
func (o *ParseRequestDto) GetModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Model, true
}

// SetModel sets field value
func (o *ParseRequestDto) SetModel(v string) {
	o.Model = v
}

// GetTextContent returns the TextContent field value
func (o *ParseRequestDto) GetTextContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TextContent
}

// GetTextContentOk returns a tuple with the TextContent field value
// and a boolean to check if the value has been set.
func (o *ParseRequestDto) GetTextContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TextContent, true
}

// SetTextContent sets field value
func (o *ParseRequestDto) SetTextContent(v string) {
	o.TextContent = v
}

func (o ParseRequestDto) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["model"] = o.Model
	}
	if true {
		toSerialize["textContent"] = o.TextContent
	}
	return json.Marshal(toSerialize)
}

type NullableParseRequestDto struct {
	value *ParseRequestDto
	isSet bool
}

func (v NullableParseRequestDto) Get() *ParseRequestDto {
	return v.value
}

func (v *NullableParseRequestDto) Set(val *ParseRequestDto) {
	v.value = val
	v.isSet = true
}

func (v NullableParseRequestDto) IsSet() bool {
	return v.isSet
}

func (v *NullableParseRequestDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableParseRequestDto(val *ParseRequestDto) *NullableParseRequestDto {
	return &NullableParseRequestDto{value: val, isSet: true}
}

func (v NullableParseRequestDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableParseRequestDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
