/*
 * Lybic core API
 *
 * Lybic core API
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package lybic

import (
	"time"
)

// MachineImagesResponseDto struct for MachineImagesResponseDto
type MachineImagesResponseDto struct {
	Images []MachineImagesResponseDtoImages `json:"images"`
	Quota  MachineImagesResponseDtoQuota    `json:"quota"`
}

// MachineImagesResponseDtoImages struct for MachineImagesResponseDtoImages
type MachineImagesResponseDtoImages struct {
	Id                  string    `json:"id"`
	Name                string    `json:"name"`
	Description         *string   `json:"description,omitempty"`
	CreatedAt           time.Time `json:"createdAt"`
	ShapeName           string    `json:"shapeName"`
	RequiredFeatureFlag *string   `json:"requiredFeatureFlag,omitempty"`
	Scope               string    `json:"scope"`  // one of "ORG", "PUBLIC"
	Status              string    `json:"status"` // one of "CREATING", "READY", "ERROR"
}

// MachineImagesResponseDtoQuota struct for MachineImagesResponseDtoQuota
type MachineImagesResponseDtoQuota struct {
	Used  int32 `json:"used"`
	Limit int32 `json:"limit"`
}
