/*
 * Lybic core API
 *
 * Lybic core API
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package lybic

// MachineImageResponseDto struct for MachineImageResponseDto
type MachineImageResponseDto = MachineImagesResponseDtoImages
