/*
 * Lybic core API
 *
 * Lybic core API
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package lybic

// SandboxFileCopyRequestDtoFiles Single file copy item
type SandboxFileCopyRequestDtoFiles struct {
	// A caller-defined unique identifier for this item. The value is included in the response to associate results with their corresponding requests
	Id string `json:"id,omitempty"`
	// Copy file source - can be one of: sandboxFileLocation, httpPutLocation, httpGetLocation, httpPostFormLocation
	Src interface{} `json:"src"`
	// Copy file destination - can be one of: sandboxFileLocation, httpPutLocation, httpGetLocation, httpPostFormLocation
	Dest interface{} `json:"dest"`
}
