/*
 * Lybic core API
 *
 * Lybic core API
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package lybic
// GetSandboxResponseDtoConnectDetails struct for GetSandboxResponseDtoConnectDetails
type GetSandboxResponseDtoConnectDetails struct {
	GatewayAddresses []GetSandboxResponseDtoConnectDetailsGatewayAddresses `json:"gatewayAddresses"`
	CertificateHashBase64 string `json:"certificateHashBase64"`
	EndUserToken string `json:"endUserToken"`
	RoomId string `json:"roomId"`
}
