// Code generated by OpenAPI Generator. DO NOT EDIT.
//
// lybic
//
// No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
//
// API version: 0.6.3
// Generated by: OpenAPI Generator (https://openapi-generator.tech)
//

package lybic

import (
	"github.com/lybic/lybic-sdk-go/pkg/json"
)

// ComputerUseActionDto struct for ComputerUseActionDto
type ComputerUseActionDto struct {
	// All possible computer use actions
	Action ComputerUseActionDtoActionOneOf `json:"action"`
	// Whether to include the screenshot url after action in the response
	IncludeScreenShot *bool `json:"includeScreenShot,omitempty"`
	// Whether to include the cursor position after action in the response
	IncludeCursorPosition *bool `json:"includeCursorPosition,omitempty"`
}

// NewComputerUseActionDto instantiates a new ComputerUseActionDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComputerUseActionDto(action ComputerUseActionDtoActionOneOf) *ComputerUseActionDto {
	this := ComputerUseActionDto{}
	this.Action = action
	var includeScreenShot = true
	this.IncludeScreenShot = &includeScreenShot
	var includeCursorPosition = true
	this.IncludeCursorPosition = &includeCursorPosition
	return &this
}

// NewComputerUseActionDtoWithDefaults instantiates a new ComputerUseActionDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComputerUseActionDtoWithDefaults() *ComputerUseActionDto {
	this := ComputerUseActionDto{}
	var includeScreenShot = true
	this.IncludeScreenShot = &includeScreenShot
	var includeCursorPosition = true
	this.IncludeCursorPosition = &includeCursorPosition
	return &this
}

// GetAction returns the Action field value
func (o *ComputerUseActionDto) GetAction() ComputerUseActionDtoActionOneOf {
	if o == nil {
		var ret ComputerUseActionDtoActionOneOf
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *ComputerUseActionDto) GetActionOk() (*ComputerUseActionDtoActionOneOf, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *ComputerUseActionDto) SetAction(v ComputerUseActionDtoActionOneOf) {
	o.Action = v
}

// GetIncludeScreenShot returns the IncludeScreenShot field value if set, zero value otherwise.
func (o *ComputerUseActionDto) GetIncludeScreenShot() bool {
	if o == nil || o.IncludeScreenShot == nil {
		var ret bool
		return ret
	}
	return *o.IncludeScreenShot
}

// GetIncludeScreenShotOk returns a tuple with the IncludeScreenShot field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComputerUseActionDto) GetIncludeScreenShotOk() (*bool, bool) {
	if o == nil || o.IncludeScreenShot == nil {
		return nil, false
	}
	return o.IncludeScreenShot, true
}

// HasIncludeScreenShot returns a boolean if a field has been set.
func (o *ComputerUseActionDto) HasIncludeScreenShot() bool {
	if o != nil && o.IncludeScreenShot != nil {
		return true
	}

	return false
}

// SetIncludeScreenShot gets a reference to the given bool and assigns it to the IncludeScreenShot field.
func (o *ComputerUseActionDto) SetIncludeScreenShot(v bool) {
	o.IncludeScreenShot = &v
}

// GetIncludeCursorPosition returns the IncludeCursorPosition field value if set, zero value otherwise.
func (o *ComputerUseActionDto) GetIncludeCursorPosition() bool {
	if o == nil || o.IncludeCursorPosition == nil {
		var ret bool
		return ret
	}
	return *o.IncludeCursorPosition
}

// GetIncludeCursorPositionOk returns a tuple with the IncludeCursorPosition field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComputerUseActionDto) GetIncludeCursorPositionOk() (*bool, bool) {
	if o == nil || o.IncludeCursorPosition == nil {
		return nil, false
	}
	return o.IncludeCursorPosition, true
}

// HasIncludeCursorPosition returns a boolean if a field has been set.
func (o *ComputerUseActionDto) HasIncludeCursorPosition() bool {
	if o != nil && o.IncludeCursorPosition != nil {
		return true
	}

	return false
}

// SetIncludeCursorPosition gets a reference to the given bool and assigns it to the IncludeCursorPosition field.
func (o *ComputerUseActionDto) SetIncludeCursorPosition(v bool) {
	o.IncludeCursorPosition = &v
}

func (o ComputerUseActionDto) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["action"] = o.Action
	}
	if o.IncludeScreenShot != nil {
		toSerialize["includeScreenShot"] = o.IncludeScreenShot
	}
	if o.IncludeCursorPosition != nil {
		toSerialize["includeCursorPosition"] = o.IncludeCursorPosition
	}
	return json.Marshal(toSerialize)
}

type NullableComputerUseActionDto struct {
	value *ComputerUseActionDto
	isSet bool
}

func (v NullableComputerUseActionDto) Get() *ComputerUseActionDto {
	return v.value
}

func (v *NullableComputerUseActionDto) Set(val *ComputerUseActionDto) {
	v.value = val
	v.isSet = true
}

func (v NullableComputerUseActionDto) IsSet() bool {
	return v.isSet
}

func (v *NullableComputerUseActionDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComputerUseActionDto(val *ComputerUseActionDto) *NullableComputerUseActionDto {
	return &NullableComputerUseActionDto{value: val, isSet: true}
}

func (v NullableComputerUseActionDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComputerUseActionDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
