/*
 * Lybic core API
 *
 * Lybic core API
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package lybic
// McpServerResponseDto struct for McpServerResponseDto
type McpServerResponseDto struct {
	// ID of the MCP server.
	Id string `json:"id"`
	// Name of the MCP server.
	Name string `json:"name"`
	// Creation date of the MCP server.
	CreatedAt string `json:"createdAt"`
	// Whether this is the default MCP server for the organization.
	DefaultMcpServer bool `json:"defaultMcpServer"`
	// Project ID to which the MCP server belongs.
	ProjectId string `json:"projectId"`
	Policy McpServerResponseDtoPolicy `json:"policy"`
	// ID of the currently connected sandbox.
	CurrentSandboxId *string `json:"currentSandboxId"`
}
