/*
 * Lybic core API
 *
 * Lybic core API
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package lybic

// SingleProjectResponseDto struct for SingleProjectResponseDto
type SingleProjectResponseDto struct {
	Id             string `json:"id"`
	Name           string `json:"name"`
	CreatedAt      string `json:"createdAt"`
	DefaultProject bool   `json:"defaultProject"`
}
