// Code generated by OpenAPI Generator. DO NOT EDIT.
//
// lybic
//
// No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
//
// API version: 0.6.3
// Generated by: OpenAPI Generator (https://openapi-generator.tech)
//

package lybic

import (
	"github.com/lybic/lybic-sdk-go/pkg/json"
)

// SetMcpServerToSandboxResponseDto struct for SetMcpServerToSandboxResponseDto
type SetMcpServerToSandboxResponseDto struct {
	// The ID of the sandbox to connect the MCP server to.
	SandboxId *string `json:"sandboxId,omitempty"`
}

// NewSetMcpServerToSandboxResponseDto instantiates a new SetMcpServerToSandboxResponseDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetMcpServerToSandboxResponseDto(sandboxId *string) *SetMcpServerToSandboxResponseDto {
	this := SetMcpServerToSandboxResponseDto{}
	this.SandboxId = sandboxId
	return &this
}

// NewSetMcpServerToSandboxResponseDtoWithDefaults instantiates a new SetMcpServerToSandboxResponseDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetMcpServerToSandboxResponseDtoWithDefaults() *SetMcpServerToSandboxResponseDto {
	this := SetMcpServerToSandboxResponseDto{}
	return &this
}

// GetSandboxId returns the SandboxId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *SetMcpServerToSandboxResponseDto) GetSandboxId() string {
	if o == nil || o.SandboxId == nil {
		var ret string
		return ret
	}

	return *o.SandboxId
}

// GetSandboxIdOk returns a tuple with the SandboxId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SetMcpServerToSandboxResponseDto) GetSandboxIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SandboxId, o.SandboxId == nil
}

// SetSandboxId sets field value
func (o *SetMcpServerToSandboxResponseDto) SetSandboxId(v string) {
	o.SandboxId = &v
}

func (o SetMcpServerToSandboxResponseDto) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["sandboxId"] = o.SandboxId
	}
	return json.Marshal(toSerialize)
}

type NullableSetMcpServerToSandboxResponseDto struct {
	value *SetMcpServerToSandboxResponseDto
	isSet bool
}

func (v NullableSetMcpServerToSandboxResponseDto) Get() *SetMcpServerToSandboxResponseDto {
	return v.value
}

func (v *NullableSetMcpServerToSandboxResponseDto) Set(val *SetMcpServerToSandboxResponseDto) {
	v.value = val
	v.isSet = true
}

func (v NullableSetMcpServerToSandboxResponseDto) IsSet() bool {
	return v.isSet
}

func (v *NullableSetMcpServerToSandboxResponseDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetMcpServerToSandboxResponseDto(val *SetMcpServerToSandboxResponseDto) *NullableSetMcpServerToSandboxResponseDto {
	return &NullableSetMcpServerToSandboxResponseDto{value: val, isSet: true}
}

func (v NullableSetMcpServerToSandboxResponseDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetMcpServerToSandboxResponseDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
