// Code generated by OpenAPI Generator. DO NOT EDIT.
//
// lybic
//
// No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
//
// API version: 0.6.3
// Generated by: OpenAPI Generator (https://openapi-generator.tech)
//

package lybic

import (
	"encoding/json"
	"time"
)

// GetSandboxResponseDtoSandbox struct for GetSandboxResponseDtoSandbox
type GetSandboxResponseDtoSandbox struct {
	Id string `json:"id"`
	Name string `json:"name"`
	ExpiredAt time.Time `json:"expiredAt"`
	CreatedAt time.Time `json:"createdAt"`
	ProjectId string `json:"projectId"`
}

// NewGetSandboxResponseDtoSandbox instantiates a new GetSandboxResponseDtoSandbox object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSandboxResponseDtoSandbox(id string, name string, expiredAt time.Time, createdAt time.Time, projectId string, ) *GetSandboxResponseDtoSandbox {
	this := GetSandboxResponseDtoSandbox{}
	this.Id = id
	this.Name = name
	this.ExpiredAt = expiredAt
	this.CreatedAt = createdAt
	this.ProjectId = projectId
	return &this
}

// NewGetSandboxResponseDtoSandboxWithDefaults instantiates a new GetSandboxResponseDtoSandbox object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSandboxResponseDtoSandboxWithDefaults() *GetSandboxResponseDtoSandbox {
	this := GetSandboxResponseDtoSandbox{}
	return &this
}

// GetId returns the Id field value
func (o *GetSandboxResponseDtoSandbox) GetId() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GetSandboxResponseDtoSandbox) GetIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GetSandboxResponseDtoSandbox) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *GetSandboxResponseDtoSandbox) GetName() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GetSandboxResponseDtoSandbox) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *GetSandboxResponseDtoSandbox) SetName(v string) {
	o.Name = v
}

// GetExpiredAt returns the ExpiredAt field value
func (o *GetSandboxResponseDtoSandbox) GetExpiredAt() time.Time {
	if o == nil  {
		var ret time.Time
		return ret
	}

	return o.ExpiredAt
}

// GetExpiredAtOk returns a tuple with the ExpiredAt field value
// and a boolean to check if the value has been set.
func (o *GetSandboxResponseDtoSandbox) GetExpiredAtOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ExpiredAt, true
}

// SetExpiredAt sets field value
func (o *GetSandboxResponseDtoSandbox) SetExpiredAt(v time.Time) {
	o.ExpiredAt = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *GetSandboxResponseDtoSandbox) GetCreatedAt() time.Time {
	if o == nil  {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *GetSandboxResponseDtoSandbox) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *GetSandboxResponseDtoSandbox) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetProjectId returns the ProjectId field value
func (o *GetSandboxResponseDtoSandbox) GetProjectId() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *GetSandboxResponseDtoSandbox) GetProjectIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *GetSandboxResponseDtoSandbox) SetProjectId(v string) {
	o.ProjectId = v
}

func (o GetSandboxResponseDtoSandbox) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["expiredAt"] = o.ExpiredAt
	}
	if true {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if true {
		toSerialize["projectId"] = o.ProjectId
	}
	return json.Marshal(toSerialize)
}

type NullableGetSandboxResponseDtoSandbox struct {
	value *GetSandboxResponseDtoSandbox
	isSet bool
}

func (v NullableGetSandboxResponseDtoSandbox) Get() *GetSandboxResponseDtoSandbox {
	return v.value
}

func (v *NullableGetSandboxResponseDtoSandbox) Set(val *GetSandboxResponseDtoSandbox) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSandboxResponseDtoSandbox) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSandboxResponseDtoSandbox) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSandboxResponseDtoSandbox(val *GetSandboxResponseDtoSandbox) *NullableGetSandboxResponseDtoSandbox {
	return &NullableGetSandboxResponseDtoSandbox{value: val, isSet: true}
}

func (v NullableGetSandboxResponseDtoSandbox) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSandboxResponseDtoSandbox) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
