// Code generated by OpenAPI Generator. DO NOT EDIT.
//
// lybic
//
// No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
//
// API version: 0.6.3
// Generated by: OpenAPI Generator (https://openapi-generator.tech)
//

package lybic

import (
	"github.com/lybic/lybic-sdk-go/pkg/json"
)

// SandboxActionResponseDtoCursorPosition struct for SandboxActionResponseDtoCursorPosition
type SandboxActionResponseDtoCursorPosition struct {
	// The x position of the cursor.
	X float32 `json:"x"`
	// The y position of the cursor.
	Y float32 `json:"y"`
	// The width of the screen.
	ScreenWidth float32 `json:"screenWidth"`
	// The height of the screen.
	ScreenHeight float32 `json:"screenHeight"`
	// The index of the screen.
	ScreenIndex float32 `json:"screenIndex"`
}

// NewSandboxActionResponseDtoCursorPosition instantiates a new SandboxActionResponseDtoCursorPosition object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSandboxActionResponseDtoCursorPosition(x float32, y float32, screenWidth float32, screenHeight float32, screenIndex float32) *SandboxActionResponseDtoCursorPosition {
	this := SandboxActionResponseDtoCursorPosition{}
	this.X = x
	this.Y = y
	this.ScreenWidth = screenWidth
	this.ScreenHeight = screenHeight
	this.ScreenIndex = screenIndex
	return &this
}

// NewSandboxActionResponseDtoCursorPositionWithDefaults instantiates a new SandboxActionResponseDtoCursorPosition object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSandboxActionResponseDtoCursorPositionWithDefaults() *SandboxActionResponseDtoCursorPosition {
	this := SandboxActionResponseDtoCursorPosition{}
	return &this
}

// GetX returns the X field value
func (o *SandboxActionResponseDtoCursorPosition) GetX() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.X
}

// GetXOk returns a tuple with the X field value
// and a boolean to check if the value has been set.
func (o *SandboxActionResponseDtoCursorPosition) GetXOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.X, true
}

// SetX sets field value
func (o *SandboxActionResponseDtoCursorPosition) SetX(v float32) {
	o.X = v
}

// GetY returns the Y field value
func (o *SandboxActionResponseDtoCursorPosition) GetY() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Y
}

// GetYOk returns a tuple with the Y field value
// and a boolean to check if the value has been set.
func (o *SandboxActionResponseDtoCursorPosition) GetYOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Y, true
}

// SetY sets field value
func (o *SandboxActionResponseDtoCursorPosition) SetY(v float32) {
	o.Y = v
}

// GetScreenWidth returns the ScreenWidth field value
func (o *SandboxActionResponseDtoCursorPosition) GetScreenWidth() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.ScreenWidth
}

// GetScreenWidthOk returns a tuple with the ScreenWidth field value
// and a boolean to check if the value has been set.
func (o *SandboxActionResponseDtoCursorPosition) GetScreenWidthOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ScreenWidth, true
}

// SetScreenWidth sets field value
func (o *SandboxActionResponseDtoCursorPosition) SetScreenWidth(v float32) {
	o.ScreenWidth = v
}

// GetScreenHeight returns the ScreenHeight field value
func (o *SandboxActionResponseDtoCursorPosition) GetScreenHeight() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.ScreenHeight
}

// GetScreenHeightOk returns a tuple with the ScreenHeight field value
// and a boolean to check if the value has been set.
func (o *SandboxActionResponseDtoCursorPosition) GetScreenHeightOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ScreenHeight, true
}

// SetScreenHeight sets field value
func (o *SandboxActionResponseDtoCursorPosition) SetScreenHeight(v float32) {
	o.ScreenHeight = v
}

// GetScreenIndex returns the ScreenIndex field value
func (o *SandboxActionResponseDtoCursorPosition) GetScreenIndex() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.ScreenIndex
}

// GetScreenIndexOk returns a tuple with the ScreenIndex field value
// and a boolean to check if the value has been set.
func (o *SandboxActionResponseDtoCursorPosition) GetScreenIndexOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ScreenIndex, true
}

// SetScreenIndex sets field value
func (o *SandboxActionResponseDtoCursorPosition) SetScreenIndex(v float32) {
	o.ScreenIndex = v
}

func (o SandboxActionResponseDtoCursorPosition) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["x"] = o.X
	}
	if true {
		toSerialize["y"] = o.Y
	}
	if true {
		toSerialize["screenWidth"] = o.ScreenWidth
	}
	if true {
		toSerialize["screenHeight"] = o.ScreenHeight
	}
	if true {
		toSerialize["screenIndex"] = o.ScreenIndex
	}
	return json.Marshal(toSerialize)
}

type NullableSandboxActionResponseDtoCursorPosition struct {
	value *SandboxActionResponseDtoCursorPosition
	isSet bool
}

func (v NullableSandboxActionResponseDtoCursorPosition) Get() *SandboxActionResponseDtoCursorPosition {
	return v.value
}

func (v *NullableSandboxActionResponseDtoCursorPosition) Set(val *SandboxActionResponseDtoCursorPosition) {
	v.value = val
	v.isSet = true
}

func (v NullableSandboxActionResponseDtoCursorPosition) IsSet() bool {
	return v.isSet
}

func (v *NullableSandboxActionResponseDtoCursorPosition) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSandboxActionResponseDtoCursorPosition(val *SandboxActionResponseDtoCursorPosition) *NullableSandboxActionResponseDtoCursorPosition {
	return &NullableSandboxActionResponseDtoCursorPosition{value: val, isSet: true}
}

func (v NullableSandboxActionResponseDtoCursorPosition) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSandboxActionResponseDtoCursorPosition) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
