/*
 * Lybic core API
 *
 * Lybic core API
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package lybic

// SandboxShellCommandReadResponseDto struct for SandboxShellCommandReadResponseDto
type SandboxShellCommandReadResponseDto struct {
	// Accumulated output parts from the shell session.
	Output []SandboxShellCommandOutput `json:"output"`
	// Whether the shell session is still running.
	IsRunning bool `json:"isRunning"`
}

// SandboxShellCommandOutput represents a discriminated union for shell output
type SandboxShellCommandOutput struct {
	// OneofKind identifies which type of output this is
	OneofKind string `json:"oneofKind"`
	// Standard output from the shell session (when oneofKind is "stdout")
	Stdout *string `json:"stdout,omitempty"`
	// Standard error output from the shell session (when oneofKind is "stderr")
	Stderr *string `json:"stderr,omitempty"`
	// Indicates a prompt waiting state (when oneofKind is "waiting")
	Waiting *bool `json:"waiting,omitempty"`
}
