/*
 * Lybic core API
 *
 * Lybic core API
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package lybic

import (
	"time"
)

// MachineImageResponseDto struct for MachineImageResponseDto
type MachineImageResponseDto struct {
	Id          string    `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	CreatedAt   time.Time `json:"createdAt"`
	ShapeName   string    `json:"shapeName"`
	Status      string    `json:"status"`
}
