/*
 * Lybic core API
 *
 * Lybic core API
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package lybic
// StatsResponseDto struct for StatsResponseDto
type StatsResponseDto struct {
	// Number of MCP servers
	McpServers float32 `json:"mcpServers"`
	// Number of sandboxes
	Sandboxes float32 `json:"sandboxes"`
	// Number of projects
	Projects float32 `json:"projects"`
}
