// Code generated by OpenAPI Generator. DO NOT EDIT.
//
// lybic
//
// No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
//
// API version: 0.8.0
// Generated by: OpenAPI Generator (https://openapi-generator.tech)

package lybic

// ParseRequestDto struct for ParseRequestDto
type ParseRequestDto struct {
	// The model to parse the input for
	Model string `json:"model"`
	// The text content to parse
	TextContent string `json:"textContent"`
}
