// Code generated by OpenAPI Generator. DO NOT EDIT.
//
// lybic
//
// No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
//
// API version: 0.8
// Generated by: OpenAPI Generator (https://openapi-generator.tech)
//

package lybic

import (
	"github.com/lybic/lybic-sdk-go/pkg/json"
)

// GetSandboxResponseDtoSandboxShape struct for GetSandboxResponseDtoSandboxShape
type GetSandboxResponseDtoSandboxShape struct {
	Name                        string `json:"name"`
	Description                 string `json:"description"`
	HardwareAcceleratedEncoding bool   `json:"hardwareAcceleratedEncoding"`
	// This price acts as a multiplier, e.g. if it is set to 0.5, each hour of usage will be billed as 0.5 hours.
	PricePerHour     float32 `json:"pricePerHour"`
	RequiredPlanTier float32 `json:"requiredPlanTier"`
	Os               string  `json:"os"`
	Virtualization   string  `json:"virtualization"`
	Architecture     string  `json:"architecture"`
}

// NewGetSandboxResponseDtoSandboxShape instantiates a new GetSandboxResponseDtoSandboxShape object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSandboxResponseDtoSandboxShape(name string, description string, hardwareAcceleratedEncoding bool, pricePerHour float32, requiredPlanTier float32, os string, virtualization string, architecture string) *GetSandboxResponseDtoSandboxShape {
	this := GetSandboxResponseDtoSandboxShape{}
	this.Name = name
	this.Description = description
	this.HardwareAcceleratedEncoding = hardwareAcceleratedEncoding
	this.PricePerHour = pricePerHour
	this.RequiredPlanTier = requiredPlanTier
	this.Os = os
	this.Virtualization = virtualization
	this.Architecture = architecture
	return &this
}

// NewGetSandboxResponseDtoSandboxShapeWithDefaults instantiates a new GetSandboxResponseDtoSandboxShape object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSandboxResponseDtoSandboxShapeWithDefaults() *GetSandboxResponseDtoSandboxShape {
	this := GetSandboxResponseDtoSandboxShape{}
	return &this
}

// GetName returns the Name field value
func (o *GetSandboxResponseDtoSandboxShape) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GetSandboxResponseDtoSandboxShape) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *GetSandboxResponseDtoSandboxShape) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value
func (o *GetSandboxResponseDtoSandboxShape) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *GetSandboxResponseDtoSandboxShape) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *GetSandboxResponseDtoSandboxShape) SetDescription(v string) {
	o.Description = v
}

// GetHardwareAcceleratedEncoding returns the HardwareAcceleratedEncoding field value
func (o *GetSandboxResponseDtoSandboxShape) GetHardwareAcceleratedEncoding() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HardwareAcceleratedEncoding
}

// GetHardwareAcceleratedEncodingOk returns a tuple with the HardwareAcceleratedEncoding field value
// and a boolean to check if the value has been set.
func (o *GetSandboxResponseDtoSandboxShape) GetHardwareAcceleratedEncodingOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HardwareAcceleratedEncoding, true
}

// SetHardwareAcceleratedEncoding sets field value
func (o *GetSandboxResponseDtoSandboxShape) SetHardwareAcceleratedEncoding(v bool) {
	o.HardwareAcceleratedEncoding = v
}

// GetPricePerHour returns the PricePerHour field value
func (o *GetSandboxResponseDtoSandboxShape) GetPricePerHour() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.PricePerHour
}

// GetPricePerHourOk returns a tuple with the PricePerHour field value
// and a boolean to check if the value has been set.
func (o *GetSandboxResponseDtoSandboxShape) GetPricePerHourOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PricePerHour, true
}

// SetPricePerHour sets field value
func (o *GetSandboxResponseDtoSandboxShape) SetPricePerHour(v float32) {
	o.PricePerHour = v
}

// GetRequiredPlanTier returns the RequiredPlanTier field value
func (o *GetSandboxResponseDtoSandboxShape) GetRequiredPlanTier() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.RequiredPlanTier
}

// GetRequiredPlanTierOk returns a tuple with the RequiredPlanTier field value
// and a boolean to check if the value has been set.
func (o *GetSandboxResponseDtoSandboxShape) GetRequiredPlanTierOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequiredPlanTier, true
}

// SetRequiredPlanTier sets field value
func (o *GetSandboxResponseDtoSandboxShape) SetRequiredPlanTier(v float32) {
	o.RequiredPlanTier = v
}

// GetOs returns the Os field value
func (o *GetSandboxResponseDtoSandboxShape) GetOs() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Os
}

// GetOsOk returns a tuple with the Os field value
// and a boolean to check if the value has been set.
func (o *GetSandboxResponseDtoSandboxShape) GetOsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Os, true
}

// SetOs sets field value
func (o *GetSandboxResponseDtoSandboxShape) SetOs(v string) {
	o.Os = v
}

// GetVirtualization returns the Virtualization field value
func (o *GetSandboxResponseDtoSandboxShape) GetVirtualization() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Virtualization
}

// GetVirtualizationOk returns a tuple with the Virtualization field value
// and a boolean to check if the value has been set.
func (o *GetSandboxResponseDtoSandboxShape) GetVirtualizationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Virtualization, true
}

// SetVirtualization sets field value
func (o *GetSandboxResponseDtoSandboxShape) SetVirtualization(v string) {
	o.Virtualization = v
}

// GetArchitecture returns the Architecture field value
func (o *GetSandboxResponseDtoSandboxShape) GetArchitecture() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Architecture
}

// GetArchitectureOk returns a tuple with the Architecture field value
// and a boolean to check if the value has been set.
func (o *GetSandboxResponseDtoSandboxShape) GetArchitectureOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Architecture, true
}

// SetArchitecture sets field value
func (o *GetSandboxResponseDtoSandboxShape) SetArchitecture(v string) {
	o.Architecture = v
}

func (o GetSandboxResponseDtoSandboxShape) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["description"] = o.Description
	}
	if true {
		toSerialize["hardwareAcceleratedEncoding"] = o.HardwareAcceleratedEncoding
	}
	if true {
		toSerialize["pricePerHour"] = o.PricePerHour
	}
	if true {
		toSerialize["requiredPlanTier"] = o.RequiredPlanTier
	}
	if true {
		toSerialize["os"] = o.Os
	}
	if true {
		toSerialize["virtualization"] = o.Virtualization
	}
	if true {
		toSerialize["architecture"] = o.Architecture
	}
	return json.Marshal(toSerialize)
}

type NullableGetSandboxResponseDtoSandboxShape struct {
	value *GetSandboxResponseDtoSandboxShape
	isSet bool
}

func (v NullableGetSandboxResponseDtoSandboxShape) Get() *GetSandboxResponseDtoSandboxShape {
	return v.value
}

func (v *NullableGetSandboxResponseDtoSandboxShape) Set(val *GetSandboxResponseDtoSandboxShape) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSandboxResponseDtoSandboxShape) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSandboxResponseDtoSandboxShape) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSandboxResponseDtoSandboxShape(val *GetSandboxResponseDtoSandboxShape) *NullableGetSandboxResponseDtoSandboxShape {
	return &NullableGetSandboxResponseDtoSandboxShape{value: val, isSet: true}
}

func (v NullableGetSandboxResponseDtoSandboxShape) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSandboxResponseDtoSandboxShape) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
