/*
 * Lybic core API
 *
 * Lybic core API
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package lybic

// SetMcpServerToSandboxResponseDto struct for SetMcpServerToSandboxResponseDto
type SetMcpServerToSandboxResponseDto struct {
	// The ID of the sandbox to connect the MCP server to.
	SandboxId *string `json:"sandboxId"`
}
