// Code generated by OpenAPI Generator. DO NOT EDIT.
//
// lybic
//
// No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
//
// API version: 0.6.3
// Generated by: OpenAPI Generator (https://openapi-generator.tech)
//

package lybic

import (
	"github.com/lybic/lybic-sdk-go/pkg/json"
)

// ComputerUseParseRequestDto struct for ComputerUseParseRequestDto
type ComputerUseParseRequestDto struct {
	// The model to parse the input for
	Model string `json:"model"`
	// The text content to parse
	TextContent string `json:"textContent"`
}

// NewComputerUseParseRequestDto instantiates a new ComputerUseParseRequestDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComputerUseParseRequestDto(model string, textContent string) *ComputerUseParseRequestDto {
	this := ComputerUseParseRequestDto{}
	this.Model = model
	this.TextContent = textContent
	return &this
}

// NewComputerUseParseRequestDtoWithDefaults instantiates a new ComputerUseParseRequestDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComputerUseParseRequestDtoWithDefaults() *ComputerUseParseRequestDto {
	this := ComputerUseParseRequestDto{}
	return &this
}

// GetModel returns the Model field value
func (o *ComputerUseParseRequestDto) GetModel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Model
}

// GetModelOk returns a tuple with the Model field value
// and a boolean to check if the value has been set.
func (o *ComputerUseParseRequestDto) GetModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Model, true
}

// SetModel sets field value
func (o *ComputerUseParseRequestDto) SetModel(v string) {
	o.Model = v
}

// GetTextContent returns the TextContent field value
func (o *ComputerUseParseRequestDto) GetTextContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TextContent
}

// GetTextContentOk returns a tuple with the TextContent field value
// and a boolean to check if the value has been set.
func (o *ComputerUseParseRequestDto) GetTextContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TextContent, true
}

// SetTextContent sets field value
func (o *ComputerUseParseRequestDto) SetTextContent(v string) {
	o.TextContent = v
}

func (o ComputerUseParseRequestDto) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["model"] = o.Model
	}
	if true {
		toSerialize["textContent"] = o.TextContent
	}
	return json.Marshal(toSerialize)
}

type NullableComputerUseParseRequestDto struct {
	value *ComputerUseParseRequestDto
	isSet bool
}

func (v NullableComputerUseParseRequestDto) Get() *ComputerUseParseRequestDto {
	return v.value
}

func (v *NullableComputerUseParseRequestDto) Set(val *ComputerUseParseRequestDto) {
	v.value = val
	v.isSet = true
}

func (v NullableComputerUseParseRequestDto) IsSet() bool {
	return v.isSet
}

func (v *NullableComputerUseParseRequestDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComputerUseParseRequestDto(val *ComputerUseParseRequestDto) *NullableComputerUseParseRequestDto {
	return &NullableComputerUseParseRequestDto{value: val, isSet: true}
}

func (v NullableComputerUseParseRequestDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComputerUseParseRequestDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
