// Code generated by OpenAPI Generator. DO NOT EDIT.
//
// lybic
//
// No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
//
// API version: 0.7.3
// Generated by: OpenAPI Generator (https://openapi-generator.tech)
//

package lybic

import (
	"github.com/lybic/lybic-sdk-go/pkg/json"
)

// ComputerUseParseTextRequestDto struct for ComputerUseParseTextRequestDto
type ComputerUseParseTextRequestDto struct {
	// The text content to parse
	TextContent string `json:"textContent"`
}

// NewComputerUseParseTextRequestDto instantiates a new ComputerUseParseTextRequestDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComputerUseParseTextRequestDto(textContent string) *ComputerUseParseTextRequestDto {
	this := ComputerUseParseTextRequestDto{}
	this.TextContent = textContent
	return &this
}

// NewComputerUseParseTextRequestDtoWithDefaults instantiates a new ComputerUseParseTextRequestDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComputerUseParseTextRequestDtoWithDefaults() *ComputerUseParseTextRequestDto {
	this := ComputerUseParseTextRequestDto{}
	return &this
}

// GetTextContent returns the TextContent field value
func (o *ComputerUseParseTextRequestDto) GetTextContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TextContent
}

// GetTextContentOk returns a tuple with the TextContent field value
// and a boolean to check if the value has been set.
func (o *ComputerUseParseTextRequestDto) GetTextContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TextContent, true
}

// SetTextContent sets field value
func (o *ComputerUseParseTextRequestDto) SetTextContent(v string) {
	o.TextContent = v
}

func (o ComputerUseParseTextRequestDto) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["textContent"] = o.TextContent
	}
	return json.Marshal(toSerialize)
}

type NullableComputerUseParseTextRequestDto struct {
	value *ComputerUseParseTextRequestDto
	isSet bool
}

func (v NullableComputerUseParseTextRequestDto) Get() *ComputerUseParseTextRequestDto {
	return v.value
}

func (v *NullableComputerUseParseTextRequestDto) Set(val *ComputerUseParseTextRequestDto) {
	v.value = val
	v.isSet = true
}

func (v NullableComputerUseParseTextRequestDto) IsSet() bool {
	return v.isSet
}

func (v *NullableComputerUseParseTextRequestDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComputerUseParseTextRequestDto(val *ComputerUseParseTextRequestDto) *NullableComputerUseParseTextRequestDto {
	return &NullableComputerUseParseTextRequestDto{value: val, isSet: true}
}

func (v NullableComputerUseParseTextRequestDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComputerUseParseTextRequestDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
