/*
 * Lybic core API
 *
 * Lybic core API
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package lybic

// GetSandboxResponseDtoConnectDetailsGatewayAddresses struct for GetSandboxResponseDtoConnectDetailsGatewayAddresses
type GetSandboxResponseDtoConnectDetailsGatewayAddresses struct {
	Address            string   `json:"address"`
	Port               float32  `json:"port"`
	Name               string   `json:"name"`
	PreferredProviders []string `json:"preferredProviders"`
	GatewayType        string   `json:"gatewayType"`
	Path               string   `json:"path,omitempty"`
}
