/*
 * Lybic core API
 *
 * Lybic core API
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package lybic

// SandboxShellCommandCreateResponseDto struct for SandboxShellCommandCreateResponseDto
type SandboxShellCommandCreateResponseDto struct {
	// The ID of the created shell session.
	SessionId string `json:"sessionId"`
}
